In [25]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import source.parsers as parsers
import source.database as database
import importlib
import os
import glob
importlib.reload(parsers)
importlib.reload(database)

In [26]:
device = "cuda"
database_folder = "./database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

DS = database.VectorDatabase(device, database_folder)
DS.info()
DS.clear_collections()
DS.create_collection()

collections: [Collection(name=documents)]
deleted data in Collection(name=documents)
created collection: Collection(name=documents) with 0 documents

In [29]:
glob_pattern = os.path.join('.', 'data', '*')
files = glob.glob(glob_pattern)

for file in files:
   DS.add_documents(file)

.\data\demo_textfile.txt
- added 1 documents, 6 chunks
.\data\HW 1 - Cave Flyer.pdf
- added 1 documents, 3 chunks
.\data\HW 2 - Complex Numbers.pdf
- added 1 documents, 3 chunks
.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
- added 1 documents, 5 chunks
.\data\HW 4 - Linearization and Dynamic Response.pdf
- added 1 documents, 2 chunks
.\data\HW 5 - Exam 1 in Matlab.pdf
- added 1 documents, 3 chunks
.\data\HW 6 - Routh Array and Root Locus.pdf
- added 1 documents, 2 chunks
.\data\HW 7 - Design Challenges.pdf
- added 1 documents, 7 chunks
.\data\HW 8 - Nyquist Stability.pdf
- added 1 documents, 1 chunks
.\data\HW 9 - Stability Margins and Compensation.pdf
- added 1 documents, 1 chunks

In [36]:
DS.add_documents(files)

.\data\demo_textfile.txt
.\data\HW 1 - Cave Flyer.pdf
.\data\HW 2 - Complex Numbers.pdf
.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
.\data\HW 4 - Linearization and Dynamic Response.pdf
.\data\HW 5 - Exam 1 in Matlab.pdf
.\data\HW 6 - Routh Array and Root Locus.pdf
.\data\HW 7 - Design Challenges.pdf
.\data\HW 8 - Nyquist Stability.pdf
.\data\HW 9 - Stability Margins and Compensation.pdf
- added 10 documents, 33 chunks

In [21]:
DS.info()

collections: [Collection(name=documents)]

In [37]:
query ="how do I install matlab"
df_results = DS.search(query, k = 10)
df_results

found 10 similar documents

   distance                                           basename                                    id                                    id       source_type tfidf pca                               page_lengths  chunk_idx file_ext                             source_id                                              title  N_chunks           modification_date                                          file_hash                                    id                                    id               creation_date         author                                           fullpath                 upload_date                                           document
0  0.467617                              HW 1 - Cave Flyer.pdf  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  chunked document    ()  ()                           (974, 2735, 291)          0     .pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36                              HW 1 - Cave Flyer.pdf         3  2024-08-25 16:26:44.119668  d235a1898843e3a439eabc58b387565f659900d5644604...  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  2025-11-26 11:27:12.507327  Sameer Shroff                       .\data\HW 1 - Cave Flyer.pdf  2025-11-30 15:07:56.649976  Carnegie Mellon University 24-451: Feedback Co...
1  0.477226                              HW 1 - Cave Flyer.pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  18b8a5c1-0e02-5935-8acb-b6b32f32ae36     full document    ()  ()                           (974, 2735, 291)         -1     .pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36                              HW 1 - Cave Flyer.pdf         0  2024-08-25 16:26:44.119668  d235a1898843e3a439eabc58b387565f659900d5644604...  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  2025-11-26 11:27:12.507327  Sameer Shroff                       .\data\HW 1 - Cave Flyer.pdf  2025-11-30 15:07:56.649976  Carnegie Mellon University 24-451: Feedback Co...
2  0.712724                       HW 7 - Design Challenges.pdf  34d76a86-10c7-52c4-b9fa-a71985820b17  34d76a86-10c7-52c4-b9fa-a71985820b17  chunked document    ()  ()  (1352, 1462, 1842, 401, 1634, 1157, 1138)          3     .pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd                       HW 7 - Design Challenges.pdf         7  2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  34d76a86-10c7-52c4-b9fa-a71985820b17  34d76a86-10c7-52c4-b9fa-a71985820b17  2025-11-26 11:27:12.514347  Sameer Shroff                .\data\HW 7 - Design Challenges.pdf  2025-11-30 15:07:58.387768  Carnegie Mellon University 24-451: Feedback Co...
3  0.733412              HW 6 - Routh Array and Root Locus.pdf  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  chunked document    ()  ()                                (2191, 957)          1     .pdf  2c2a9853-3781-5770-8e9f-c5726b15291d              HW 6 - Routh Array and Root Locus.pdf         2  2023-10-04 17:23:37.193000  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  2025-11-26 11:27:12.513349  Sameer Shroff       .\data\HW 6 - Routh Array and Root Locus.pdf  2025-11-30 15:07:57.199821  • # 7c only.  Use Simulink.  Hint: 𝐾1 will be ...
4  0.748144                         HW 2 - Complex Numbers.pdf  31d1eafa-c729-54c6-ac3d-5255371c96e7  31d1eafa-c729-54c6-ac3d-5255371c96e7  chunked document    ()  ()                          (1937, 1550, 600)          1     .pdf  41fc35d3-e8dd-5ea0-9c4f-fea6a7d36787                         HW 2 - Complex Numbers.pdf         3  2024-08-27 20:24:40.731488  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  31d1eafa-c729-54c6-ac3d-5255371c96e7  31d1eafa-c729-54c6-ac3d-5255371c96e7  2025-11-26 11:27:12.508334  Sameer Shroff                  .\data\HW 2 - Complex Numbers.pdf  2025-11-30 15:07:56.768043  axis). \n7. Consider a set of points that form...
5  0.753956                       HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  79afc125-4d4f-5e0b-9447-f0e0b3238bbd     full document    ()  ()  (1352, 1462, 1842, 401, 1634, 1157, 1138)         -1     .pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd                       HW 7 - Design Challenges.pdf         0  2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  2025-11-26 11:27:12.514347  Sameer Shroff                .\data\HW 7 - Design Challenges.pdf  2025-11-30 15:07:58.387768  Carnegie Mellon University 24-451: Feedback Co...
6  0.753956                       HW 7 - Design Challenges.pdf  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  chunked document    ()  ()  (1352, 1462, 1842, 401, 1634, 1157, 1138)          0     .pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd                       HW 7 - Design Challenges.pdf         7  2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  2025-11-26 11:27:12.514347  Sameer Shroff                .\data\HW 7 - Design Challenges.pdf  2025-11-30 15:07:58.387768  Carnegie Mellon University 24-451: Feedback Co...
7  0.755669  HW 3 - Laplace Transforms and Intro to Control...  2f69e529-3bc2-5a92-874b-b6721ac6adf4  2f69e529-3bc2-5a92-874b-b6721ac6adf4  chunked document    ()  ()                    (2363, 1621, 1323, 682)          3     .pdf  dc14db90-fbd5-55d7-bf3e-dbca0e531fe1  HW 3 - Laplace Transforms and Intro to Control...         5  2022-09-07 20:37:59.854000  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2f69e529-3bc2-5a92-874b-b6721ac6adf4  2f69e529-3bc2-5a92-874b-b6721ac6adf4  2025-11-26 11:27:12.509331  Sameer Shroff  .\data\HW 3 - Laplace Transforms and Intro to ...  2025-11-30 15:07:56.950035  Carnegie Mellon University 24-451: Feedback Co...
8  0.757500                        HW 5 - Exam 1 in Matlab.pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334  8bf3b706-bed9-57bb-b088-6a6ca5278334     full document    ()  ()                         (1749, 2024, 1216)         -1     .pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334                        HW 5 - Exam 1 in Matlab.pdf         0  2024-09-25 17:53:25.497000  910573961d42ea022be07ca314325b4400a963f89e1795...  8bf3b706-bed9-57bb-b088-6a6ca5278334  8bf3b706-bed9-57bb-b088-6a6ca5278334  2025-11-26 11:27:12.511332  Sameer Shroff                 .\data\HW 5 - Exam 1 in Matlab.pdf  2025-11-30 15:07:57.128847  Carnegie Mellon University 24-451: Feedback Co...
9  0.757500                        HW 5 - Exam 1 in Matlab.pdf  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  chunked document    ()  ()                         (1749, 2024, 1216)          0     .pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334                        HW 5 - Exam 1 in Matlab.pdf         3  2024-09-25 17:53:25.497000  910573961d42ea022be07ca314325b4400a963f89e1795...  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  2025-11-26 11:27:12.511332  Sameer Shroff                 .\data\HW 5 - Exam 1 in Matlab.pdf  2025-11-30 15:07:57.128847  Carnegie Mellon University 24-451: Feedback Co...

In [38]:
query ="what options do I have to install matlab in detail"
response = DS.query(query, k = 10)
print(response.content)

found 10 similar documents
You have the following options to install or run MATLAB:

*   **Download and install MATLAB locally**: You can download and install MATLAB on your own computer. For more details, refer to [https://www.cmu.edu/computing/software/all/matlab/](https://www.cmu.edu/computing/software/all/matlab/).
*   **Run MATLAB online through a browser**: You can access and use MATLAB through your web browser. For more information, visit [https://www.mathworks.com/products/matlab-online.html](https://www.mathworks.com/products/matlab-online.html).
*   **Run MATLAB through a Virtual Andrew session**: You can use MATLAB within a Virtual Andrew session. Instructions for this can be found at [https://www.cmu.edu/computing/services/endpoint/software/managed-desktops/how-to/virtual-andrew.html](https://www.cmu.edu/computing/services/endpoint/software/managed-desktops/how-to/virtual-andrew.html).

(source: HW 1 - Cave Flyer.pdf)

In [39]:
DS.collection.get()

{'ids': ['c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a',
  'd00a351a-96b3-560b-8b31-f7dab9abc247',
  'ac16fb33-1007-5f21-badf-51326739eae1',
  '6e75dfa6-61ce-5d73-9f0b-97e593b36e70',
  '7f7ee21b-13c6-5bd6-927b-45ae4a2d217a',
  '2443d291-d7bc-5b92-a554-04af388319a1',
  '6387ac27-fb24-5a6b-9830-4c22a1923477',
  '18b8a5c1-0e02-5935-8acb-b6b32f32ae36',
  '84d1843d-1bd1-53b8-ae55-2c2c939cdb37',
  'a6a533b9-7542-5de9-997e-a8bf62a2567d',
  '8db318ca-8016-52e1-895a-b94b73bf5866',
  '41fc35d3-e8dd-5ea0-9c4f-fea6a7d36787',
  'b5d3bc77-d338-5180-965f-5f40c72baed2',
  '31d1eafa-c729-54c6-ac3d-5255371c96e7',
  'af0e56d4-5e39-52fb-9a06-f6bb1c058b49',
  'dc14db90-fbd5-55d7-bf3e-dbca0e531fe1',
  '2cd378ca-b422-51cb-9571-1bd060000b9b',
  'a15a1017-2f3c-53dd-b46b-b1e946be0626',
  'f2b9c5c1-9186-5c6f-a312-18e0acb3184c',
  '2f69e529-3bc2-5a92-874b-b6721ac6adf4',
  '02ef51c4-8f87-552e-8832-f72ed1df50ef',
  '80db1571-34fa-53aa-8a56-b39681278855',
  '07d9494a-ea63-53ef-8cb4-07742beb9abb',
  '62b4072a-1df9-55d9-a9a3-457666485e0c',
  '8bf3b706-bed9-57bb-b088-6a6ca5278334',
  '66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce',
  'fd404feb-816b-5840-b735-a1266097fa05',
  'a8aa1388-28e7-5e69-9266-2b9048abfce8',
  '2c2a9853-3781-5770-8e9f-c5726b15291d',
  '633cf765-5101-537d-944a-50becd881f81',
  'c6aeca0f-6ea7-585e-b995-1cf9b71baef3',
  '79afc125-4d4f-5e0b-9447-f0e0b3238bbd',
  'a9b7e972-fbf0-5ff5-af3c-19fba77410f6',
  '83b8a84b-a11d-5cb1-b2d7-758e1d86b895',
  '6da8d02a-6ffa-5410-8915-cb4992b2a3e0',
  '34d76a86-10c7-52c4-b9fa-a71985820b17',
  '27094245-284d-571e-8e0d-4f4a1ebb03f6',
  '4b983cb4-395e-5079-a6f3-89783cc878ac',
  'c1c38fd3-bf54-54af-b292-b4bdda4fb016',
  '0e0c2f7c-e486-585a-ba6d-fe94b0b26e03',
  'c6566691-5068-5848-a341-39c0910c40bc',
  '662b39f1-3edc-5e7c-97a5-86a3af255560',
  '9e5afc2a-3f98-5a8b-b375-24fa92c0cd58'],
 'embeddings': None,
 'documents': ["In Congress, July 4, 1776\n\nThe unanimous Declaration of the thirteen united States of America, When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.\n\nWe hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.--That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, --That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness. Prudence, indeed, will dictate that Governments long established should not be changed for light and transient causes; and accordingly all experience hath shewn, that mankind are more disposed to suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they are accustomed. But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.--Such has been the patient sufferance of these Colonies; and such is now the necessity which constrains them to alter their former Systems of Government. The history of the present King of Great Britain is a history of repeated injuries and usurpations, all having in direct object the establishment of an absolute Tyranny over these States. To prove this, let Facts be submitted to a candid world.\n\nHe has refused his Assent to Laws, the most wholesome and necessary for the public good.\n\nHe has forbidden his Governors to pass Laws of immediate and pressing importance, unless suspended in their operation till his Assent should be obtained; and when so suspended, he has utterly neglected to attend to them.\n\nHe has refused to pass other Laws for the accommodation of large districts of people, unless those people would relinquish the right of Representation in the Legislature, a right inestimable to them and formidable to tyrants only.\n\nHe has called together legislative bodies at places unusual, uncomfortable, and distant from the depository of their public Records, for the sole purpose of fatiguing them into compliance with his measures.\n\nHe has dissolved Representative Houses repeatedly, for opposing with manly firmness his invasions on the rights of the people.\n\nHe has refused for a long time, after such dissolutions, to cause others to be elected; whereby the Legislative powers, incapable of Annihilation, have returned to the People at large for their exercise; the State remaining in the mean time exposed to all the dangers of invasion from without, and convulsions within.\n\nHe has endeavoured to prevent the population of these States; for that purpose obstructing the Laws for Naturalization of Foreigners; refusing to pass others to encourage their migrations hither, and raising the conditions of new Appropriations of Lands.\n\nHe has obstructed the Administration of Justice, by refusing his Assent to Laws for establishing Judiciary powers.\n\nHe has made Judges dependent on his Will alone, for the tenure of their offices, and the amount and payment of their salaries.\n\nHe has erected a multitude of New Offices, and sent hither swarms of Officers to harrass our people, and eat out their substance.\n\nHe has kept among us, in times of peace, Standing Armies without the Consent of our legislatures.\n\nHe has affected to render the Military independent of and superior to the Civil power.\n\nHe has combined with others to subject us to a jurisdiction foreign to our constitution, and unacknowledged by our laws; giving his Assent to their Acts of pretended Legislation:\n\nFor Quartering large bodies of armed troops among us:\n\nFor protecting them, by a mock Trial, from punishment for any Murders which they should commit on the Inhabitants of these States:\n\nFor cutting off our Trade with all parts of the world:\n\nFor imposing Taxes on us without our Consent:\n\nFor depriving us in many cases, of the benefits of Trial by Jury:\n\nFor transporting us beyond Seas to be tried for pretended offences:\n\nFor abolishing the free System of English Laws in a neighbouring Province, establishing therein an Arbitrary government, and enlarging its Boundaries so as to render it at once an example and fit instrument for introducing the same absolute rule into these Colonies:\n\nFor taking away our Charters, abolishing our most valuable Laws, and altering fundamentally the Forms of our Governments:\n\nFor suspending our own Legislatures, and declaring themselves invested with power to legislate for us in all cases whatsoever.\n\nHe has abdicated Government here, by declaring us out of his Protection and waging War against us.\n\nHe has plundered our seas, ravaged our Coasts, burnt our towns, and destroyed the lives of our people.\n\nHe is at this time transporting large Armies of foreign Mercenaries to compleat the works of death, desolation and tyranny, already begun with circumstances of Cruelty & perfidy scarcely paralleled in the most barbarous ages, and totally unworthy the Head of a civilized nation.\n\nHe has constrained our fellow Citizens taken Captive on the high Seas to bear Arms against their Country, to become the executioners of their friends and Brethren, or to fall themselves by their Hands.\n\nHe has excited domestic insurrections amongst us, and has endeavoured to bring on the inhabitants of our frontiers, the merciless Indian Savages, whose known rule of warfare, is an undistinguished destruction of all ages, sexes and conditions.\n\nIn every stage of these Oppressions We have Petitioned for Redress in the most humble terms: Our repeated Petitions have been answered only by repeated injury. A Prince, whose character is thus marked by every act which may define a Tyrant, is unfit to be the ruler of a free people.\n\nNor have We been wanting in attentions to our Brittish brethren. We have warned them from time to time of attempts by their legislature to extend an unwarrantable jurisdiction over us. We have reminded them of the circumstances of our emigration and settlement here. We have appealed to their native justice and magnanimity, and we have conjured them by the ties of our common kindred to disavow these usurpations, which, would inevitably interrupt our connections and correspondence. They too have been deaf to the voice of justice and of consanguinity. We must, therefore, acquiesce in the necessity, which denounces our Separation, and hold them, as we hold the rest of mankind, Enemies in War, in Peace Friends.\n\nWe, therefore, the Representatives of the united States of America, in General Congress, Assembled, appealing to the Supreme Judge of the world for the rectitude of our intentions, do, in the Name, and by Authority of the good People of these Colonies, solemnly publish and declare, That these United Colonies are, and of Right ought to be Free and Independent States; that they are Absolved from all Allegiance to the British Crown, and that all political connection between them and the State of Great Britain, is and ought to be totally dissolved; and that as Free and Independent States, they have full Power to levy War, conclude Peace, contract Alliances, establish Commerce, and to do all other Acts and Things which Independent States may of right do. And for the support of this Declaration, with a firm reliance on the protection of divine Providence, we mutually pledge to each other our Lives, our Fortunes and our sacred Honor.",
  "In Congress, July 4, 1776\n\nThe unanimous Declaration of the thirteen united States of America, When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.",
  'We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.--That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, --That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness. Prudence, indeed, will dictate that Governments long established should not be changed for light and transient causes; and accordingly all experience hath shewn, that mankind are more disposed to suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they are accustomed. But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.--Such has been the patient sufferance of these Colonies; and such is now the necessity which constrains them to alter their former Systems of Government. The history of the present King of Great Britain is a history of repeated injuries and usurpations, all having in direct object the establishment of an absolute Tyranny over these States. To prove this, let Facts be submitted to a candid world.\n\nHe has refused his Assent to Laws, the most wholesome and necessary for the public good.\n\nHe has forbidden his Governors to pass Laws of immediate and pressing importance, unless suspended in their operation till his Assent should be obtained; and when so suspended, he has utterly neglected to attend to them.',
  'He has forbidden his Governors to pass Laws of immediate and pressing importance, unless suspended in their operation till his Assent should be obtained; and when so suspended, he has utterly neglected to attend to them.\n\nHe has refused to pass other Laws for the accommodation of large districts of people, unless those people would relinquish the right of Representation in the Legislature, a right inestimable to them and formidable to tyrants only.\n\nHe has called together legislative bodies at places unusual, uncomfortable, and distant from the depository of their public Records, for the sole purpose of fatiguing them into compliance with his measures.\n\nHe has dissolved Representative Houses repeatedly, for opposing with manly firmness his invasions on the rights of the people.\n\nHe has refused for a long time, after such dissolutions, to cause others to be elected; whereby the Legislative powers, incapable of Annihilation, have returned to the People at large for their exercise; the State remaining in the mean time exposed to all the dangers of invasion from without, and convulsions within.\n\nHe has endeavoured to prevent the population of these States; for that purpose obstructing the Laws for Naturalization of Foreigners; refusing to pass others to encourage their migrations hither, and raising the conditions of new Appropriations of Lands.\n\nHe has obstructed the Administration of Justice, by refusing his Assent to Laws for establishing Judiciary powers.\n\nHe has made Judges dependent on his Will alone, for the tenure of their offices, and the amount and payment of their salaries.\n\nHe has erected a multitude of New Offices, and sent hither swarms of Officers to harrass our people, and eat out their substance.\n\nHe has kept among us, in times of peace, Standing Armies without the Consent of our legislatures.\n\nHe has affected to render the Military independent of and superior to the Civil power.',
  'He has kept among us, in times of peace, Standing Armies without the Consent of our legislatures.\n\nHe has affected to render the Military independent of and superior to the Civil power.\n\nHe has combined with others to subject us to a jurisdiction foreign to our constitution, and unacknowledged by our laws; giving his Assent to their Acts of pretended Legislation:\n\nFor Quartering large bodies of armed troops among us:\n\nFor protecting them, by a mock Trial, from punishment for any Murders which they should commit on the Inhabitants of these States:\n\nFor cutting off our Trade with all parts of the world:\n\nFor imposing Taxes on us without our Consent:\n\nFor depriving us in many cases, of the benefits of Trial by Jury:\n\nFor transporting us beyond Seas to be tried for pretended offences:\n\nFor abolishing the free System of English Laws in a neighbouring Province, establishing therein an Arbitrary government, and enlarging its Boundaries so as to render it at once an example and fit instrument for introducing the same absolute rule into these Colonies:\n\nFor taking away our Charters, abolishing our most valuable Laws, and altering fundamentally the Forms of our Governments:\n\nFor suspending our own Legislatures, and declaring themselves invested with power to legislate for us in all cases whatsoever.\n\nHe has abdicated Government here, by declaring us out of his Protection and waging War against us.\n\nHe has plundered our seas, ravaged our Coasts, burnt our towns, and destroyed the lives of our people.\n\nHe is at this time transporting large Armies of foreign Mercenaries to compleat the works of death, desolation and tyranny, already begun with circumstances of Cruelty & perfidy scarcely paralleled in the most barbarous ages, and totally unworthy the Head of a civilized nation.\n\nHe has constrained our fellow Citizens taken Captive on the high Seas to bear Arms against their Country, to become the executioners of their friends and Brethren, or to fall themselves by their Hands.',
  'He has constrained our fellow Citizens taken Captive on the high Seas to bear Arms against their Country, to become the executioners of their friends and Brethren, or to fall themselves by their Hands.\n\nHe has excited domestic insurrections amongst us, and has endeavoured to bring on the inhabitants of our frontiers, the merciless Indian Savages, whose known rule of warfare, is an undistinguished destruction of all ages, sexes and conditions.\n\nIn every stage of these Oppressions We have Petitioned for Redress in the most humble terms: Our repeated Petitions have been answered only by repeated injury. A Prince, whose character is thus marked by every act which may define a Tyrant, is unfit to be the ruler of a free people.\n\nNor have We been wanting in attentions to our Brittish brethren. We have warned them from time to time of attempts by their legislature to extend an unwarrantable jurisdiction over us. We have reminded them of the circumstances of our emigration and settlement here. We have appealed to their native justice and magnanimity, and we have conjured them by the ties of our common kindred to disavow these usurpations, which, would inevitably interrupt our connections and correspondence. They too have been deaf to the voice of justice and of consanguinity. We must, therefore, acquiesce in the necessity, which denounces our Separation, and hold them, as we hold the rest of mankind, Enemies in War, in Peace Friends.',
  'We, therefore, the Representatives of the united States of America, in General Congress, Assembled, appealing to the Supreme Judge of the world for the rectitude of our intentions, do, in the Name, and by Authority of the good People of these Colonies, solemnly publish and declare, That these United Colonies are, and of Right ought to be Free and Independent States; that they are Absolved from all Allegiance to the British Crown, and that all political connection between them and the State of Great Britain, is and ought to be totally dissolved; and that as Free and Independent States, they have full Power to levy War, conclude Peace, contract Alliances, establish Commerce, and to do all other Acts and Things which Independent States may of right do. And for the support of this Declaration, with a firm reliance on the protection of divine Providence, we mutually pledge to each other our Lives, our Fortunes and our sacred Honor.',

In [24]:
DS.compute_pca()

AttributeError: 'VectorDatabase' object has no attribute 'compute_pca'

In [ ]:
labels, inertia, df_pca = DS.run_kmeans(n_clusters = 3)
df_pca

                                         pca_0     pca_1     pca_2     pca_3     pca_4     pca_5     pca_6     pca_7     pca_8     pca_9    pca_10    pca_11    pca_12    pca_13    pca_14    pca_15    pca_16    pca_17    pca_18    pca_19    pca_20    pca_21    pca_22    pca_23    pca_24    pca_25    pca_26    pca_27    pca_28    pca_29    pca_30    pca_31    pca_32    pca_33    pca_34    pca_35    pca_36    pca_37    pca_38    pca_39    pca_40    pca_41    pca_42    pca_43    pca_44    pca_45    pca_46    pca_47    pca_48    pca_49    pca_50    pca_51    pca_52    pca_53    pca_54    pca_55    pca_56  pca_57  pca_58
7353459a-33c2-544c-81f2-4e8877cddfcc -0.097473  0.023911  0.404297  0.123596 -0.044678 -0.191650 -0.105103  0.284668  0.090149  0.191895  0.212036  0.049622  0.157959 -0.012924 -0.103882 -0.110474 -0.038361  0.108032  0.043884 -0.095276  0.120422 -0.054108 -0.064026 -0.006313 -0.025238 -0.047363 -0.026718  0.067017  0.056427 -0.009048  0.030624  0.017227  0.001927  0.021255 -0.014137 -0.010353  0.017822  0.005661 -0.017075 -0.024445 -0.011375 -0.004311 -0.007507  0.016754  0.008163  0.004921 -0.009583  0.005924 -0.012108 -0.001997  0.002077 -0.002522  0.007568  0.013435  0.026901  0.038269  0.001522    -0.0     0.0
3dc8bb69-454a-535c-9815-02ae4e274a4f  0.379395 -0.236328  0.203735  0.020264 -0.132568  0.264648  0.022995  0.056427 -0.270508 -0.085876  0.068726 -0.038147 -0.092590 -0.161377 -0.008499 -0.092163 -0.024323 -0.068298  0.068970  0.008553 -0.041504 -0.010902 -0.028015  0.110962  0.002043  0.084778 -0.042358  0.046265  0.038239 -0.023895  0.049133  0.064575 -0.064758 -0.031403  0.049225 -0.031204  0.032715  0.003504  0.002792  0.024887  0.004379 -0.043365  0.014145  0.024796 -0.032166 -0.012032 -0.008881 -0.001143  0.004749 -0.000172  0.002567 -0.003546 -0.002533 -0.001260  0.005260  0.000632 -0.023254    -0.0     0.0
92843a15-ddf5-51b5-b851-ed3b159a4e25 -0.202026 -0.345703  0.504883  0.128418 -0.142334 -0.077881  0.184692 -0.223999  0.110291  0.186401 -0.299072 -0.084412 -0.107727  0.054596 -0.072449 -0.065063  0.035095  0.046326  0.080017  0.066284 -0.043060  0.013184  0.049896 -0.003101  0.000798 -0.000573 -0.016876 -0.018890 -0.021057  0.005207  0.005890 -0.016312 -0.001168  0.018341  0.025421  0.013672 -0.002172 -0.024200 -0.015480  0.012848 -0.001431  0.007488 -0.011650 -0.005959  0.016541 -0.009270  0.020523  0.005798  0.009270 -0.054596  0.050201 -0.039642  0.044678  0.002205 -0.003706 -0.002375  0.000022    -0.0     0.0
eb7dbac7-1c3e-59c6-ba88-06afd7217d81 -0.147705 -0.039734  0.125000 -0.253174 -0.197144  0.105835 -0.268555 -0.065979  0.044342 -0.213501  0.076904 -0.341064  0.032623 -0.042175  0.004562 -0.058899  0.076111  0.081421 -0.123230 -0.022675  0.030365 -0.037170 -0.016342  0.031982  0.079956 -0.078674 -0.041473 -0.073425 -0.057800  0.032593  0.004246  0.001627  0.018616  0.034302  0.023117  0.007957 -0.048462 -0.006432 -0.014511 -0.010651  0.017853 -0.003691 -0.001976 -0.008224 -0.000726 -0.004879 -0.014091  0.002180 -0.000116  0.006020  0.001966 -0.001649  0.001304 -0.000312 -0.000065 -0.000304  0.000169    -0.0    -0.0
aca9ef5a-8288-54e0-8231-4268d682efd2 -0.190430 -0.133057 -0.096863 -0.204712 -0.094116 -0.157104  0.200562  0.118103 -0.053558  0.097595 -0.009293 -0.133301  0.066956  0.013596  0.152466  0.131104 -0.050476 -0.009880  0.058533 -0.105652 -0.065857 -0.055542 -0.013664  0.111450  0.010101  0.001257  0.003708  0.022827 -0.022614  0.040436  0.016708 -0.012489  0.084595 -0.067810 -0.031738  0.078003 -0.007553  0.028473  0.023453 -0.015717  0.018524 -0.022537 -0.005428  0.002623 -0.041077 -0.027939 -0.008636  0.031586  0.000028 -0.067871  0.026489  0.004845 -0.064209 -0.003679  0.000682  0.002855  0.000837    -0.0     0.0
7f0fa013-0289-5477-987f-29511a387622 -0.123108 -0.272949 -0.099243 -0.112366 -0.015457 -0.017975 -0.184204 -0.045715 -0.048340 -0.075684 -0.106812  0.147217 -0.056030  0.073364 -0.156006  0.125366 -0.193115 -0.020279 -0.123047 -0.074402  0.021027 -0.007038 -0.014282  0.062103 -0.140259  0.019592 -0.103699  0.032104  0.046173  0.079285  0.013756 -0.014771  0.014153  0.022018  0.014580  0.000215 -0.041290 -0.050598 -0.011856  0.025299 -0.027969  0.012009  0.002075 -0.027939  0.030029  0.027374 -0.002907  0.010834  0.015060 -0.012421 -0.064880 -0.064270 -0.016495  0.004490  0.000653 -0.000857 -0.000174    -0.0     0.0
8a5a4e88-6b39-5898-8682-6953f1a90da7 -0.033386 -0.207031 -0.095337  0.043060  0.011024 -0.074829 -0.091003  0.202393 -0.097473 -0.097839 -0.120789  0.020432  0.024307  0.088562  0.053894 -0.118774  0.101746 -0.012848 -0.016586  0.120972  0.045227  0.047791 -0.009941  0.044128 -0.005047  0.012871  0.116638 -0.014740  0.011490  0.044098 -0.018387 -0.015388  0.054382  0.053192  0.036530  0.016083  0.037842 -0.010239  0.002043  0.036163  0.002337 -0.004742 -0.046722  0.027618  0.010063  0.012650 -0.027008 -0.091064 -0.038635 -0.060669 -0.053192  0.037445  0.017197  0.010063 -0.019028  0.009598 -0.001311    -0.0     0.0
b58c24f9-36c9-5332-8d5c-c363e1ab26be -0.012215 -0.343262 -0.161011  0.113770  0.010155 -0.145142 -0.020691 -0.105591 -0.008057 -0.076477  0.068481  0.179077  0.081726 -0.161377  0.141479 -0.049103  0.051117  0.086365  0.042786 -0.022949 -0.054474  0.016586  0.033752 -0.076294  0.037201 -0.097900 -0.115356  0.004154  0.019638 -0.060638 -0.077209 -0.047363  0.025330 -0.026367  0.049133 -0.017288 -0.020538  0.021561 -0.036255  0.050781 -0.030807  0.000293  0.004009 -0.019684 -0.009697 -0.035248 -0.018814  0.011269 -0.008797 -0.031860 -0.027328  0.019409  0.014427 -0.008537  0.037567 -0.023300  0.001309    -0.0     0.0
0eacdba8-9efd-59ce-816a-366d8cf519a9 -0.171631 -0.300293 -0.043915  0.240723  0.167114 -0.070374  0.006599 -0.133789 -0.120117  0.056091  0.248901 -0.097595  0.010117 -0.054474 -0.038605  0.197998  0.075989  0.063232 -0.047119  0.128052  0.081299  0.087097  0.083008 -0.035797 -0.006756  0.061157  0.020676 -0.008873  0.012238  0.024933  0.024551  0.037628 -0.031372 -0.009079 -0.001306  0.029282 -0.000233  0.020813  0.015388 -0.058655 -0.011139  0.008575 -0.007175  0.008621 -0.006001  0.032623  0.010651 -0.009827  0.011314 -0.005291 -0.010109 -0.003567  0.005573 -0.059906 -0.002028  0.013710  0.000299    -0.0     0.0

In [ ]:
id = DS.collection.get(limit = 1)['ids'][0]
df = DS.search_by_id(id, k =10, where = {'source_type':'full document'})
print(df)

       distance                                           basename                                    id  N_chunks                             source_id               creation_date    source_type                               page_lengths file_ext  chunk_idx                 upload_date                                                pca         author                                           fullpath           modification_date                                               hash                                           document
0  3.576279e-07                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc         0  7353459a-33c2-544c-81f2-4e8877cddfcc  2025-11-26 11:27:12.507327  full document                           [974, 2735, 291]     .pdf         -1  2025-11-28 23:46:52.237318  [-0.09745040145997666, 0.0239056972048863, 0.4...  Sameer Shroff                       .\data\HW 1 - Cave Flyer.pdf  2024-08-25 16:26:44.119668  d235a1898843e3a439eabc58b387565f659900d5644604...  Carnegie Mellon University 24-451: Feedback Co...
1  4.009807e-01                       HW 7 - Design Challenges.pdf  8a5a4e88-6b39-5898-8682-6953f1a90da7         0  8a5a4e88-6b39-5898-8682-6953f1a90da7  2025-11-26 11:27:12.514347  full document  [1352, 1462, 1842, 401, 1634, 1157, 1138]     .pdf         -1  2025-11-28 23:46:53.688009  [-0.033397547548804814, -0.2070083680654652, -...  Sameer Shroff                .\data\HW 7 - Design Challenges.pdf  2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  Carnegie Mellon University 24-451: Feedback Co...
2  4.437943e-01                        HW 5 - Exam 1 in Matlab.pdf  aca9ef5a-8288-54e0-8231-4268d682efd2         0  aca9ef5a-8288-54e0-8231-4268d682efd2  2025-11-26 11:27:12.511332  full document                         [1749, 2024, 1216]     .pdf         -1  2025-11-28 23:46:53.285213  [-0.1904676541166523, -0.13307204027003494, -0...  Sameer Shroff                 .\data\HW 5 - Exam 1 in Matlab.pdf  2024-09-25 17:53:25.497000  910573961d42ea022be07ca314325b4400a963f89e1795...  Carnegie Mellon University 24-451: Feedback Co...
3  4.689484e-01      HW 9 - Stability Margins and Compensation.pdf  0eacdba8-9efd-59ce-816a-366d8cf519a9         0  0eacdba8-9efd-59ce-816a-366d8cf519a9  2025-11-26 11:27:12.516346  full document                                     [1682]     .pdf         -1  2025-11-28 23:46:55.123613  [-0.1715749821662112, -0.300254976348345, -0.0...  Sameer Shroff  .\data\HW 9 - Stability Margins and Compensati...  2024-10-23 09:08:41.972093  9a6a2b527b59828fc47564fb9c95b4c5a24597e9d328fb...  Carnegie Mellon University 24-451: Feedback Co...
4  4.818359e-01                       HW 8 - Nyquist Stability.pdf  b58c24f9-36c9-5332-8d5c-c363e1ab26be         0  b58c24f9-36c9-5332-8d5c-c363e1ab26be  2025-11-26 11:27:12.515346  full document                                     [1230]     .pdf         -1  2025-11-28 23:46:54.962095  [-0.012212717280018255, -0.3432190166218551, -...  Sameer Shroff                .\data\HW 8 - Nyquist Stability.pdf  2022-10-23 12:32:44.015152  4623910fab2a942e48d87d03a7a14a78f2a37819210fa8...  Carnegie Mellon University 24-451: Feedback Co...
5  4.869819e-01      HW 4 - Linearization and Dynamic Response.pdf  eb7dbac7-1c3e-59c6-ba88-06afd7217d81         0  eb7dbac7-1c3e-59c6-ba88-06afd7217d81  2025-11-26 11:27:12.510332  full document                                [1457, 659]     .pdf         -1  2025-11-28 23:46:53.097486  [-0.14765964738550874, -0.039737873715005353, ...  Sameer Shroff  .\data\HW 4 - Linearization and Dynamic Respon...         2020-09-23 07:28:23  c1f105d224226dbd40b5158fd249c8a06f7711bbd80f9b...  Carnegie Mellon University 24-451: Feedback Co...
6  4.988220e-01  HW 3 - Laplace Transforms and Intro to Control...  92843a15-ddf5-51b5-b851-ed3b159a4e25         0  92843a15-ddf5-51b5-b851-ed3b159a4e25  2025-11-26 11:27:12.509331  full document                    [2363, 1621, 1323, 682]     .pdf         -1  2025-11-28 23:46:52.818393  [-0.20201848082993792, -0.3458179490897861, 0....  Sameer Shroff  .\data\HW 3 - Laplace Transforms and Intro to ...  2022-09-07 20:37:59.854000  b907d592332785225f53963d7e64d3379ba273adfb78ba...  Carnegie Mellon University 24-451: Feedback Co...
7  5.028403e-01              HW 6 - Routh Array and Root Locus.pdf  7f0fa013-0289-5477-987f-29511a387622         0  7f0fa013-0289-5477-987f-29511a387622  2025-11-26 11:27:12.513349  full document                                [2191, 957]     .pdf         -1  2025-11-28 23:46:53.506439  [-0.12312544081913634, -0.272924053555092, -0....  Sameer Shroff       .\data\HW 6 - Routh Array and Root Locus.pdf  2023-10-04 17:23:37.193000  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  Carnegie Mellon University 24-451: Feedback Co...
8  5.448520e-01                         HW 2 - Complex Numbers.pdf  3dc8bb69-454a-535c-9815-02ae4e274a4f         0  3dc8bb69-454a-535c-9815-02ae4e274a4f  2025-11-26 11:27:12.508334  full document                          [1937, 1550, 600]     .pdf         -1  2025-11-28 23:46:52.594257  [0.37945585105624025, -0.23634997581372721, 0....  Sameer Shroff                  .\data\HW 2 - Complex Numbers.pdf  2024-08-27 20:24:40.731488  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  Carnegie Mellon University 24-451: Feedback Co...

In [ ]:
import pandas as pd

id = DS.collection.get(limit = 1)['ids'][0]
r = DS.collection.get(id, include = ['embeddings'])
embedding = r['embeddings']
results = DS.collection.query(query_embeddings=embedding, include=['distances', 'metadatas', 'documents'])
df_results= shroff_rag._results_to_df(results)[0]
df_results = df_results.sort_values('distance')
df_results

       distance                                           basename                                    id               creation_date  chunk_idx file_ext                                                pca       source_type                             source_id  N_chunks                 upload_date                                           fullpath                               page_lengths         author                                               hash           modification_date                                           document
0  3.576279e-07                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc  2025-11-26 11:27:12.507327         -1     .pdf  [-0.09745040145997666, 0.0239056972048863, 0.4...     full document  7353459a-33c2-544c-81f2-4e8877cddfcc         0  2025-11-28 23:46:52.237318                       .\data\HW 1 - Cave Flyer.pdf                           [974, 2735, 291]  Sameer Shroff  d235a1898843e3a439eabc58b387565f659900d5644604...  2024-08-25 16:26:44.119668  Carnegie Mellon University 24-451: Feedback Co...
1  6.156325e-03                              HW 1 - Cave Flyer.pdf  286dd1fb-d5c2-5c3c-9e1f-65edc0aeb8df  2025-11-26 11:27:12.507327          0     .pdf  [-0.09567961068889143, 0.029872929615534234, 0...  chunked document  7353459a-33c2-544c-81f2-4e8877cddfcc         5  2025-11-28 23:46:52.237318                       .\data\HW 1 - Cave Flyer.pdf                           [974, 2735, 291]  Sameer Shroff  d235a1898843e3a439eabc58b387565f659900d5644604...  2024-08-25 16:26:44.119668  Carnegie Mellon University 24-451: Feedback Co...
2  3.589152e-01  HW 3 - Laplace Transforms and Intro to Control...  199f260c-8442-5ee7-922c-c5dcdee6441e  2025-11-26 11:27:12.509331          1     .pdf  [-0.14951696490511152, 0.02112588252143664, 0....  chunked document  92843a15-ddf5-51b5-b851-ed3b159a4e25         8  2025-11-28 23:46:52.818393  .\data\HW 3 - Laplace Transforms and Intro to ...                    [2363, 1621, 1323, 682]  Sameer Shroff  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2022-09-07 20:37:59.854000  not discussed in class).   \n4. Typical contro...
3  3.937255e-01                       HW 7 - Design Challenges.pdf  1655f1d1-9623-577e-8de7-e4a6cb26cf74  2025-11-26 11:27:12.514347          0     .pdf  [-0.02772100684287592, -0.20169627866021034, -...  chunked document  8a5a4e88-6b39-5898-8682-6953f1a90da7        13  2025-11-28 23:46:53.688009                .\data\HW 7 - Design Challenges.pdf  [1352, 1462, 1842, 401, 1634, 1157, 1138]  Sameer Shroff  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  Carnegie Mellon University 24-451: Feedback Co...
4  4.009807e-01                       HW 7 - Design Challenges.pdf  8a5a4e88-6b39-5898-8682-6953f1a90da7  2025-11-26 11:27:12.514347         -1     .pdf  [-0.033397547548804814, -0.2070083680654652, -...     full document  8a5a4e88-6b39-5898-8682-6953f1a90da7         0  2025-11-28 23:46:53.688009                .\data\HW 7 - Design Challenges.pdf  [1352, 1462, 1842, 401, 1634, 1157, 1138]  Sameer Shroff  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  Carnegie Mellon University 24-451: Feedback Co...
5  4.276317e-01              HW 6 - Routh Array and Root Locus.pdf  6d68a7b5-9426-57b7-8336-d3682cf2bd87  2025-11-26 11:27:12.513349          2     .pdf  [-0.031672400647115385, -0.12534593047786177, ...  chunked document  7f0fa013-0289-5477-987f-29511a387622         4  2025-11-28 23:46:53.506439       .\data\HW 6 - Routh Array and Root Locus.pdf                                [2191, 957]  Sameer Shroff  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  2023-10-04 17:23:37.193000  Do problems:  \n• # 4.  Hint: for the closed l...
6  4.437943e-01                        HW 5 - Exam 1 in Matlab.pdf  aca9ef5a-8288-54e0-8231-4268d682efd2  2025-11-26 11:27:12.511332         -1     .pdf  [-0.1904676541166523, -0.13307204027003494, -0...     full document  aca9ef5a-8288-54e0-8231-4268d682efd2         0  2025-11-28 23:46:53.285213                 .\data\HW 5 - Exam 1 in Matlab.pdf                         [1749, 2024, 1216]  Sameer Shroff  910573961d42ea022be07ca314325b4400a963f89e1795...  2024-09-25 17:53:25.497000  Carnegie Mellon University 24-451: Feedback Co...
7  4.439000e-01                       HW 7 - Design Challenges.pdf  6eadf3ed-8569-5c4f-b491-ddc82800b339  2025-11-26 11:27:12.514347          4     .pdf  [-0.14179743010144524, -0.10353334333602214, -...  chunked document  8a5a4e88-6b39-5898-8682-6953f1a90da7        13  2025-11-28 23:46:53.688009                .\data\HW 7 - Design Challenges.pdf  [1352, 1462, 1842, 401, 1634, 1157, 1138]  Sameer Shroff  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  Carnegie Mellon University 24-451: Feedback Co...
8  4.447445e-01                        HW 5 - Exam 1 in Matlab.pdf  eeb26b35-3cab-51fa-a773-66e4a9e2eceb  2025-11-26 11:27:12.511332          0     .pdf  [-0.17971123092363642, -0.13044921506346033, -...  chunked document  aca9ef5a-8288-54e0-8231-4268d682efd2         7  2025-11-28 23:46:53.285213                 .\data\HW 5 - Exam 1 in Matlab.pdf                         [1749, 2024, 1216]  Sameer Shroff  910573961d42ea022be07ca314325b4400a963f89e1795...  2024-09-25 17:53:25.497000  Carnegie Mellon University 24-451: Feedback Co...
9  4.689484e-01      HW 9 - Stability Margins and Compensation.pdf  0eacdba8-9efd-59ce-816a-366d8cf519a9  2025-11-26 11:27:12.516346         -1     .pdf  [-0.1715749821662112, -0.300254976348345, -0.0...     full document  0eacdba8-9efd-59ce-816a-366d8cf519a9         0  2025-11-28 23:46:55.123613  .\data\HW 9 - Stability Margins and Compensati...                                     [1682]  Sameer Shroff  9a6a2b527b59828fc47564fb9c95b4c5a24597e9d328fb...  2024-10-23 09:08:41.972093  Carnegie Mellon University 24-451: Feedback Co...

In [ ]:
limit = 5
offset = 0
while True:
    # Retrieve a batch of records
    results = DS.collection.get(limit=limit, offset=offset)

    # Process the retrieved documents
    if results['documents']:
        for i, doc in enumerate(results['documents']):
            print(f"ID: {results['ids'][i]}")
        
        # Increment offset for the next batch
        offset += limit
    else:
        # No more documents, break the loop
        break
#known_hashes = [x['hash'] for x in DS.collection.get()['metadatas']]

ID: 7353459a-33c2-544c-81f2-4e8877cddfcc
ID: 286dd1fb-d5c2-5c3c-9e1f-65edc0aeb8df
ID: bb8a65b5-8740-50f1-a48e-e1bc737957ae
ID: 5f2af6a1-d4ed-5cd7-8d7e-04b6c8379b32
ID: 2a20b234-5ede-5cc7-8e10-ae19ba7bae54
ID: a0ffd146-d919-5853-8b24-dc58390a6961
ID: 3dc8bb69-454a-535c-9815-02ae4e274a4f
ID: 38bcd366-2330-50ae-ad7b-3cdb3a426c96
ID: f0df46a3-317c-55ea-bffb-001935962310
ID: 489e0389-319f-5ec8-bc01-58676eda648a
ID: 6076d21e-309f-503b-8b94-92aed712855a
ID: 72d817db-a202-5596-bf34-3d04f534f3f5
ID: 9c0e90fc-1820-5b9d-8531-295933d26daf
ID: 92843a15-ddf5-51b5-b851-ed3b159a4e25
ID: d4893d3f-32e0-531c-b2f4-cb2429f2af61
ID: 199f260c-8442-5ee7-922c-c5dcdee6441e
ID: 151e02b3-accc-51ca-a5c4-7797b83ee9f6
ID: 17e0aed3-e9e5-598d-8c44-9713909ac02b
ID: d565e3d5-bb86-5c8d-a0db-8e7c306c4ec9
ID: 121a3bd2-c4e5-5c0c-bb89-af7cb2a4b2fe
ID: e6b1a814-bf34-5b7d-81d3-1ba20f1d2abf
ID: 9f86f7bc-4f1f-5724-b35d-2b6281a40d36
ID: eb7dbac7-1c3e-59c6-ba88-06afd7217d81
ID: e24eca49-a2e1-5479-847b-4fe6e0fc0c80
ID: 22d89850-939c-5304-8f4c-d6f1a4668e1f
ID: 8ce22ed3-70ae-59fa-bf3b-fd7f00b85d40
ID: aca9ef5a-8288-54e0-8231-4268d682efd2
ID: eeb26b35-3cab-51fa-a773-66e4a9e2eceb
ID: 4c4abd4d-27ba-5f82-adc8-3d78ed84a695
ID: d918bbc5-8fad-5bd4-af4f-ed37b83eb40a
ID: 8d06f776-49e4-564a-b5ec-5e351330e2ae
ID: dfff7e2b-2b77-5fd2-ab9e-2e182985b12a
ID: 15b76003-d0a0-5a90-9a56-4b9bfeb84b82
ID: 75109778-7246-572c-80a1-fa5378f2fa37
ID: 7f0fa013-0289-5477-987f-29511a387622
ID: 1f2afbbb-b38c-5d81-b989-62fde16bc4a2
ID: b00c342c-ce9b-54d5-88d4-1f8af2ac6532
ID: 6d68a7b5-9426-57b7-8336-d3682cf2bd87
ID: 4e67badd-1f8e-557f-9fd7-5d0b41adac92
ID: 8a5a4e88-6b39-5898-8682-6953f1a90da7
ID: 1655f1d1-9623-577e-8de7-e4a6cb26cf74
ID: dbcd0cd3-4e42-53de-b4db-80aa6ae90c14
ID: f19f0eb6-27b3-5007-9095-d7f9a4bb79bf
ID: dcca7ea2-5dd9-5ed2-8ba3-72a5e86c2ca5
ID: 6eadf3ed-8569-5c4f-b491-ddc82800b339
ID: 284d8524-78a9-53d9-8629-7fe707ec23e8
ID: fab77206-6a47-5286-a889-5a78ff477a92
ID: 077608f1-b3de-5b2f-a2f7-df6a68bfcf4f
ID: 41261ac6-02d8-5ac3-8df4-aa64ba705520
ID: b6800cc2-c9cd-54cb-8138-7e67794cc7ce
ID: 75c7ff24-4995-5abc-a78c-579894fefba5
ID: 2b886823-289b-5726-b4bb-ca70e3d6e417
ID: 59383c8b-2d7b-5969-a69c-7af12e7cb360
ID: b58c24f9-36c9-5332-8d5c-c363e1ab26be
ID: 7bddb56d-8239-5058-b230-ef8cb50d7f75
ID: 3bf00c85-72c3-5d44-9f7a-3f030fab52b4
ID: 0eacdba8-9efd-59ce-816a-366d8cf519a9
ID: 3cc4be9c-2cc3-5bf6-96c1-10e8858d9e5d
ID: 10a477ce-df59-574e-b10c-25d896beff93