In [1]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import source.parsers as parsers
import source.database as database
import importlib
import os
import glob
importlib.reload(parsers)
importlib.reload(database)
import pandas as pd

In [2]:
device = "cuda"
database_folder = "./database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

VD = database.VectorDatabase(device, database_folder)
VD.info()
VD.clear_collections()
VD.create_collection()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records
deleted data in Collection(name=documents)

`torch_dtype` is deprecated! Use `dtype` instead!

created collection: Collection(name=documents) with 0 documents

In [3]:
glob_pattern = os.path.join('.', 'data', '*')
files = glob.glob(glob_pattern)

for file in files:
   VD.add_documents(file)

.\data\demo_textfile.txt
- added 1 documents, 6 chunks
.\data\HW 1 - Cave Flyer.pdf
- added 1 documents, 3 chunks
.\data\HW 2 - Complex Numbers.pdf
- added 1 documents, 3 chunks
.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
- added 1 documents, 5 chunks
.\data\HW 4 - Linearization and Dynamic Response.pdf
- added 1 documents, 2 chunks
.\data\HW 5 - Exam 1 in Matlab.pdf
- added 1 documents, 3 chunks
.\data\HW 6 - Routh Array and Root Locus.pdf
- added 1 documents, 2 chunks
.\data\HW 7 - Design Challenges.pdf
- added 1 documents, 7 chunks
.\data\HW 8 - Nyquist Stability.pdf
- added 1 documents, 1 chunks
.\data\HW 9 - Stability Margins and Compensation.pdf
- added 1 documents, 1 chunks

In [4]:
VD.info()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records

In [13]:
results = VD.collection.query(query_texts='test')
df_results = database._results_to_df(results, keep_cols = ['id', 'document'], document_length_limit= 10)
df_results

                                     id     document
0  6387ac27-fb24-5a6b-9830-4c22a1923477   We, theref
1  6387ac27-fb24-5a6b-9830-4c22a1923477   He has for
2  6387ac27-fb24-5a6b-9830-4c22a1923477   He has kep
3  6387ac27-fb24-5a6b-9830-4c22a1923477   In Congres
4  6387ac27-fb24-5a6b-9830-4c22a1923477   Carnegie M
5  6387ac27-fb24-5a6b-9830-4c22a1923477   timepoints
6  6387ac27-fb24-5a6b-9830-4c22a1923477  axis). \n7.
7  6387ac27-fb24-5a6b-9830-4c22a1923477   Carnegie M
8  6387ac27-fb24-5a6b-9830-4c22a1923477   In Congres
9  6387ac27-fb24-5a6b-9830-4c22a1923477   (https://d

In [6]:
query ="how do I install matlab"
df_results = VD.search(query, k = 10)
df_results

found 10 similar documents

   distance                                    id                                           document                upload_date              creation_date  chunk_idx                                           fullpath                             source_id          modification_date                                          file_hash       source_type file_ext  N_chunks                                           basename         author pca tfidf                                              title                               page_lengths
0  0.467617  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:23.093342 2025-11-26 11:27:12.507327          0                       .\data\HW 1 - Cave Flyer.pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36 2024-08-25 16:26:44.119668  d235a1898843e3a439eabc58b387565f659900d5644604...  chunked document     .pdf         3                              HW 1 - Cave Flyer.pdf  Sameer Shroff  ()    ()                              HW 1 - Cave Flyer.pdf                           (974, 2735, 291)
1  0.477226  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:23.093342 2025-11-26 11:27:12.507327         -1                       .\data\HW 1 - Cave Flyer.pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36 2024-08-25 16:26:44.119668  d235a1898843e3a439eabc58b387565f659900d5644604...     full document     .pdf         0                              HW 1 - Cave Flyer.pdf  Sameer Shroff  ()    ()                              HW 1 - Cave Flyer.pdf                           (974, 2735, 291)
2  0.712732  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:25.108447 2025-11-26 11:27:12.514347          3                .\data\HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd 2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  chunked document     .pdf         7                       HW 7 - Design Challenges.pdf  Sameer Shroff  ()    ()                       HW 7 - Design Challenges.pdf  (1352, 1462, 1842, 401, 1634, 1157, 1138)
3  0.733412  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  • # 7c only.  Use Simulink.  Hint: 𝐾1 will be ... 2025-11-30 20:20:24.014962 2025-11-26 11:27:12.513349          1       .\data\HW 6 - Routh Array and Root Locus.pdf  2c2a9853-3781-5770-8e9f-c5726b15291d 2023-10-04 17:23:37.193000  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  chunked document     .pdf         2              HW 6 - Routh Array and Root Locus.pdf  Sameer Shroff  ()    ()              HW 6 - Routh Array and Root Locus.pdf                                (2191, 957)
4  0.748144  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  axis). \n7. Consider a set of points that form... 2025-11-30 20:20:23.391281 2025-11-26 11:27:12.508334          1                  .\data\HW 2 - Complex Numbers.pdf  41fc35d3-e8dd-5ea0-9c4f-fea6a7d36787 2024-08-27 20:24:40.731488  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  chunked document     .pdf         3                         HW 2 - Complex Numbers.pdf  Sameer Shroff  ()    ()                         HW 2 - Complex Numbers.pdf                          (1937, 1550, 600)
5  0.753922  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:25.108447 2025-11-26 11:27:12.514347         -1                .\data\HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd 2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...     full document     .pdf         0                       HW 7 - Design Challenges.pdf  Sameer Shroff  ()    ()                       HW 7 - Design Challenges.pdf  (1352, 1462, 1842, 401, 1634, 1157, 1138)
6  0.753922  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:25.108447 2025-11-26 11:27:12.514347          0                .\data\HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd 2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  chunked document     .pdf         7                       HW 7 - Design Challenges.pdf  Sameer Shroff  ()    ()                       HW 7 - Design Challenges.pdf  (1352, 1462, 1842, 401, 1634, 1157, 1138)
7  0.755635  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:23.602836 2025-11-26 11:27:12.509331          3  .\data\HW 3 - Laplace Transforms and Intro to ...  dc14db90-fbd5-55d7-bf3e-dbca0e531fe1 2022-09-07 20:37:59.854000  b907d592332785225f53963d7e64d3379ba273adfb78ba...  chunked document     .pdf         5  HW 3 - Laplace Transforms and Intro to Control...  Sameer Shroff  ()    ()  HW 3 - Laplace Transforms and Intro to Control...                    (2363, 1621, 1323, 682)
8  0.757500  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:23.887726 2025-11-26 11:27:12.511332         -1                 .\data\HW 5 - Exam 1 in Matlab.pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334 2024-09-25 17:53:25.497000  910573961d42ea022be07ca314325b4400a963f89e1795...     full document     .pdf         0                        HW 5 - Exam 1 in Matlab.pdf  Sameer Shroff  ()    ()                        HW 5 - Exam 1 in Matlab.pdf                         (1749, 2024, 1216)
9  0.757500  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co... 2025-11-30 20:20:23.887726 2025-11-26 11:27:12.511332          0                 .\data\HW 5 - Exam 1 in Matlab.pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334 2024-09-25 17:53:25.497000  910573961d42ea022be07ca314325b4400a963f89e1795...  chunked document     .pdf         3                        HW 5 - Exam 1 in Matlab.pdf  Sameer Shroff  ()    ()                        HW 5 - Exam 1 in Matlab.pdf                         (1749, 2024, 1216)

In [7]:
query ="what options do I have to install matlab in detail"
response = VD.query(query, k = 10)
print(response.content)

found 10 similar documents
You have three options to install and run MATLAB:

1.  **Download and install MATLAB locally:** You can download and install MATLAB on your own computer by following the instructions at https://www.cmu.edu/computing/software/all/matlab/.
2.  **Run MATLAB online through a browser:** You can access and use MATLAB through your web browser by visiting https://www.mathworks.com/products/matlab-online.html.
3.  **Run MATLAB through a Virtual Andrew session:** You can run MATLAB via a Virtual Andrew session. Instructions for this method can be found at https://www.cmu.edu/computing/services/endpoint/software/managed-desktops/how-to/virtual-andrew.html.

(source: HW 1 - Cave Flyer.pdf)

In [8]:
import pandas as pd
import ast




def results_to_df(results, document_length_limit = None):

    d = {}
    if 'distances' in results.keys():
        d['distance'] = results['distances']
    if 'ids' in results.keys():
        d['id'] = results['ids']
    if 'documents' in results.keys():  
        d['document'] = results['documents']
    if 'embeddings' in results.keys():
        d['embedding'] = [row for row in results['embeddings']]
    df = pd.DataFrame.from_dict(d)

    if 'metadatas' in results.keys():
        df_metadata = pd.DataFrame(results['metadatas'], index = range(len(df))).drop(columns = 'id')
        df = pd.concat([df, df_metadata], axis = 1).reset_index(drop = True)

    datetime_format =  r"%Y-%m-%d %H:%M:%S.%f"
    type_converter = {}
    type_converter['creation_date'] = lambda x:  pd.to_datetime(x, format = datetime_format)
    type_converter['upload_date'] = lambda x:  pd.to_datetime(x, format = datetime_format)
    type_converter['modification_date'] = lambda x:  pd.to_datetime(x, format = datetime_format)
    type_converter['page_lengths'] = lambda x:  x.apply(ast.literal_eval)
    type_converter['document'] = lambda x:  x.str[:document_length_limit]

    for col in df.columns:
        if col in type_converter.keys():
            df[col] = type_converter[col](df[col])

    return df


results = VD.collection.get(
        limit=10,
        offset=0,
        include=['documents', 'metadatas', 'embeddings'] # Specify what to include
    )


df = results_to_df(results, document_length_limit= 6)

df

                                     id document                                          embedding                      fullpath                upload_date         author                  title               basename pca       source_type          modification_date      page_lengths                                          file_hash  chunk_idx tfidf              creation_date                             source_id file_ext  N_chunks
0  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a   In Con  [-0.07415771484375, 0.04840087890625, -0.00752...      .\data\demo_textfile.txt 2025-11-30 20:20:22.739203                     demo_textfile.txt      demo_textfile.txt  ()     full document 2025-11-29 23:40:34.881779           (8149,)  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...         -1    () 2025-11-29 23:39:54.799670  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt         0
1  d00a351a-96b3-560b-8b31-f7dab9abc247   In Con  [-0.023284912109375, 0.0201263427734375, 0.014...      .\data\demo_textfile.txt 2025-11-30 20:20:22.739203                     demo_textfile.txt      demo_textfile.txt  ()  chunked document 2025-11-29 23:40:34.881779           (8149,)  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...          0    () 2025-11-29 23:39:54.799670  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt         6
2  ac16fb33-1007-5f21-badf-51326739eae1   We hol  [-0.0821533203125, 0.09283447265625, -0.040832...      .\data\demo_textfile.txt 2025-11-30 20:20:22.739203                     demo_textfile.txt      demo_textfile.txt  ()  chunked document 2025-11-29 23:40:34.881779           (8149,)  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...          1    () 2025-11-29 23:39:54.799670  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt         6
3  6e75dfa6-61ce-5d73-9f0b-97e593b36e70   He has  [0.00510406494140625, 0.018402099609375, 0.054...      .\data\demo_textfile.txt 2025-11-30 20:20:22.739203                     demo_textfile.txt      demo_textfile.txt  ()  chunked document 2025-11-29 23:40:34.881779           (8149,)  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...          2    () 2025-11-29 23:39:54.799670  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt         6
4  7f7ee21b-13c6-5bd6-927b-45ae4a2d217a   He has  [-0.02313232421875, 0.051055908203125, 0.01858...      .\data\demo_textfile.txt 2025-11-30 20:20:22.739203                     demo_textfile.txt      demo_textfile.txt  ()  chunked document 2025-11-29 23:40:34.881779           (8149,)  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...          3    () 2025-11-29 23:39:54.799670  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt         6
5  2443d291-d7bc-5b92-a554-04af388319a1   He has  [-0.025146484375, 0.0798339769244194, 0.005710...      .\data\demo_textfile.txt 2025-11-30 20:20:22.739203                     demo_textfile.txt      demo_textfile.txt  ()  chunked document 2025-11-29 23:40:34.881779           (8149,)  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...          4    () 2025-11-29 23:39:54.799670  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt         6
6  6387ac27-fb24-5a6b-9830-4c22a1923477   We, th  [-0.057647705078125, -0.0270538330078125, 0.00...      .\data\demo_textfile.txt 2025-11-30 20:20:22.739203                     demo_textfile.txt      demo_textfile.txt  ()  chunked document 2025-11-29 23:40:34.881779           (8149,)  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...          5    () 2025-11-29 23:39:54.799670  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt         6
7  18b8a5c1-0e02-5935-8acb-b6b32f32ae36   Carneg  [-0.021697998046875, -0.01471710205078125, -0....  .\data\HW 1 - Cave Flyer.pdf 2025-11-30 20:20:23.093342  Sameer Shroff  HW 1 - Cave Flyer.pdf  HW 1 - Cave Flyer.pdf  ()     full document 2024-08-25 16:26:44.119668  (974, 2735, 291)  d235a1898843e3a439eabc58b387565f659900d5644604...         -1    () 2025-11-26 11:27:12.507327  18b8a5c1-0e02-5935-8acb-b6b32f32ae36     .pdf         0
8  84d1843d-1bd1-53b8-ae55-2c2c939cdb37   Carneg  [-0.020050048828125, -0.002834320068359375, -0...  .\data\HW 1 - Cave Flyer.pdf 2025-11-30 20:20:23.093342  Sameer Shroff  HW 1 - Cave Flyer.pdf  HW 1 - Cave Flyer.pdf  ()  chunked document 2024-08-25 16:26:44.119668  (974, 2735, 291)  d235a1898843e3a439eabc58b387565f659900d5644604...          0    () 2025-11-26 11:27:12.507327  18b8a5c1-0e02-5935-8acb-b6b32f32ae36     .pdf         3
9  a6a533b9-7542-5de9-997e-a8bf62a2567d   Carneg  [0.0684204176068306, 0.0518188513815403, -0.07...  .\data\HW 1 - Cave Flyer.pdf 2025-11-30 20:20:23.093342  Sameer Shroff  HW 1 - Cave Flyer.pdf  HW 1 - Cave Flyer.pdf  ()  chunked document 2024-08-25 16:26:44.119668  (974, 2735, 291)  d235a1898843e3a439eabc58b387565f659900d5644604...          1    () 2025-11-26 11:27:12.507327  18b8a5c1-0e02-5935-8acb-b6b32f32ae36     .pdf         3

In [9]:
# labels, inertia, df_pca = DS.run_kmeans(n_clusters = 3)
# df_pca

In [10]:
# id = DS.collection.get(limit = 1)['ids'][0]
# df = DS.search_by_id(id, k =10, where = {'source_type':'full document'})
# print(df)

In [11]:
# import pandas as pd

# id = DS.collection.get(limit = 1)['ids'][0]
# r = DS.collection.get(id, include = ['embeddings'])
# embedding = r['embeddings']
# results = DS.collection.query(query_embeddings=embedding, include=['distances', 'metadatas', 'documents'])
# df_results= shroff_rag._results_to_df(results)[0]
# df_results = df_results.sort_values('distance')
# df_results