In [70]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import source.parsers as parsers
import source.database as database
import importlib
import os
import glob
importlib.reload(parsers)
importlib.reload(database)
import pandas as pd

In [71]:
device = "cuda"
database_folder = "./database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

VD = database.VectorDatabase(device, database_folder)
VD.info()
#VD.clear_collections()
VD.create_collection()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records
created collection: Collection(name=documents) with 10 documents

In [72]:
glob_pattern = os.path.join('.', 'data', '*')
files = glob.glob(glob_pattern)

for file in files:
   VD.add_documents(file)

- [.\data\demo_textfile.txt] already exists in database, skipping
- [.\data\HW 1 - Cave Flyer.pdf] already exists in database, skipping
- [.\data\HW 2 - Complex Numbers.pdf] already exists in database, skipping
- [.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf] already exists in database, skipping
- [.\data\HW 4 - Linearization and Dynamic Response.pdf] already exists in database, skipping
- [.\data\HW 5 - Exam 1 in Matlab.pdf] already exists in database, skipping
- [.\data\HW 6 - Routh Array and Root Locus.pdf] already exists in database, skipping
- [.\data\HW 7 - Design Challenges.pdf] already exists in database, skipping
- [.\data\HW 8 - Nyquist Stability.pdf] already exists in database, skipping
- [.\data\HW 9 - Stability Margins and Compensation.pdf] already exists in database, skipping

In [73]:
VD.info()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records

In [74]:
results = VD.collection.query(query_texts='test', include = ['embeddings'])
df_results = database._results_to_df(results, keep_cols = ['id', 'document', 'embedding'], document_length_limit= 10)
df_results

                                     id                                          embedding
0  6387ac27-fb24-5a6b-9830-4c22a1923477  [-0.05762237, -0.027064253, 0.004228827, -0.07...
1  6e75dfa6-61ce-5d73-9f0b-97e593b36e70  [0.005074929, 0.018376281, 0.054546963, -0.008...
2  7f7ee21b-13c6-5bd6-927b-45ae4a2d217a  [-0.023129955, 0.05091389, 0.018541131, -0.097...
3  d00a351a-96b3-560b-8b31-f7dab9abc247  [-0.02332572, 0.020089306, 0.014753894, -0.009...
4  fd404feb-816b-5840-b735-a1266097fa05  [-0.07055518, -0.024154782, -0.0155108655, 0.0...
5  a15a1017-2f3c-53dd-b46b-b1e946be0626  [-0.07547421, -0.059211448, -0.07448537, -0.04...
6  31d1eafa-c729-54c6-ac3d-5255371c96e7  [-0.10168264, -0.034086492, -0.030255552, 0.01...
7  a6a533b9-7542-5de9-997e-a8bf62a2567d  [0.06839764, 0.05173537, -0.075441815, -0.0258...
8  b620ba0a-f2d0-5893-8fb0-f5611726f076  [-0.074165896, 0.048336823, -0.007595239, 0.00...
9  8db318ca-8016-52e1-895a-b94b73bf5866  [-0.018426241, -0.029481918, 0.061187252, 0.00...

In [75]:
query ="how do I install matlab"
df_results = VD.search(query, k = 10)
df_results

found 10 similar documents

   distance                                    id                                           document                             source_id                                           basename         author  N_chunks   modification_date                               page_lengths         upload_date  kmeans_cluster_idx                                          file_hash                                              title                                      pca_embedding       source_type       creation_date                                           fullpath  chunk_idx file_ext
0  0.467690  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co...  278661f7-8e8d-5a6b-b0e9-3a795d3c1d75                              HW 1 - Cave Flyer.pdf  Sameer Shroff         3 2024-08-25 16:26:44                           (974, 2735, 291) 2025-12-02 07:58:08                   3  d235a1898843e3a439eabc58b387565f659900d5644604...                              HW 1 - Cave Flyer.pdf  [0.1943941, -0.04695838, -0.4651027, -0.022004...  chunked document 2025-11-26 11:27:12                       .\data\HW 1 - Cave Flyer.pdf          0     .pdf
1  0.477406  278661f7-8e8d-5a6b-b0e9-3a795d3c1d75  Carnegie Mellon University 24-451: Feedback Co...  278661f7-8e8d-5a6b-b0e9-3a795d3c1d75                              HW 1 - Cave Flyer.pdf  Sameer Shroff         0 2024-08-25 16:26:44                           (974, 2735, 291) 2025-12-02 07:58:08                   3  d235a1898843e3a439eabc58b387565f659900d5644604...                              HW 1 - Cave Flyer.pdf  [0.19473673, -0.05693338, -0.45915636, -0.0141...     full document 2025-11-26 11:27:12                       .\data\HW 1 - Cave Flyer.pdf         -1     .pdf
2  0.712826  34d76a86-10c7-52c4-b9fa-a71985820b17  Carnegie Mellon University 24-451: Feedback Co...  ad157204-5bfd-5c8f-b7e0-8e1091b814ab                       HW 7 - Design Challenges.pdf  Sameer Shroff         7 2022-10-23 12:31:27  (1352, 1462, 1842, 401, 1634, 1157, 1138) 2025-12-02 07:58:10                   1  abec6a608c256b197114106e8843696d0ea0cf2fff8710...                       HW 7 - Design Challenges.pdf  [0.19296512, 0.089894734, 0.0039551253, -0.227...  chunked document 2025-11-26 11:27:12                .\data\HW 7 - Design Challenges.pdf          3     .pdf
3  0.733397  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  • # 7c only.  Use Simulink.  Hint: 𝐾1 will be ...  566ede87-b00d-52ae-9f8d-d8ee8b019ab8              HW 6 - Routh Array and Root Locus.pdf  Sameer Shroff         2 2023-10-04 17:23:37                                (2191, 957) 2025-12-02 07:58:09                   1  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...              HW 6 - Routh Array and Root Locus.pdf  [0.3097695, 0.1719774, 0.03516554, -0.00881333...  chunked document 2025-11-26 11:27:12       .\data\HW 6 - Routh Array and Root Locus.pdf          1     .pdf
4  0.748378  31d1eafa-c729-54c6-ac3d-5255371c96e7  axis). \n7. Consider a set of points that form...  6b05026a-6866-5d10-9f05-55d96590efd0                         HW 2 - Complex Numbers.pdf  Sameer Shroff         3 2024-08-27 20:24:40                          (1937, 1550, 600) 2025-12-02 07:58:08                   2  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...                         HW 2 - Complex Numbers.pdf  [0.07369657, 0.2930621, -0.040320616, 0.564432...  chunked document 2025-11-26 11:27:12                  .\data\HW 2 - Complex Numbers.pdf          1     .pdf
5  0.754025  ad157204-5bfd-5c8f-b7e0-8e1091b814ab  Carnegie Mellon University 24-451: Feedback Co...  ad157204-5bfd-5c8f-b7e0-8e1091b814ab                       HW 7 - Design Challenges.pdf  Sameer Shroff         0 2022-10-23 12:31:27  (1352, 1462, 1842, 401, 1634, 1157, 1138) 2025-12-02 07:58:10                   1  abec6a608c256b197114106e8843696d0ea0cf2fff8710...                       HW 7 - Design Challenges.pdf  [0.3407485, -0.011094809, 0.08646353, 0.057305...     full document 2025-11-26 11:27:12                .\data\HW 7 - Design Challenges.pdf         -1     .pdf
6  0.754025  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  Carnegie Mellon University 24-451: Feedback Co...  ad157204-5bfd-5c8f-b7e0-8e1091b814ab                       HW 7 - Design Challenges.pdf  Sameer Shroff         7 2022-10-23 12:31:27  (1352, 1462, 1842, 401, 1634, 1157, 1138) 2025-12-02 07:58:10                   1  abec6a608c256b197114106e8843696d0ea0cf2fff8710...                       HW 7 - Design Challenges.pdf  [0.3407485, -0.011094809, 0.08646353, 0.057305...  chunked document 2025-11-26 11:27:12                .\data\HW 7 - Design Challenges.pdf          0     .pdf
7  0.755816  2f69e529-3bc2-5a92-874b-b6721ac6adf4  Carnegie Mellon University 24-451: Feedback Co...  7b199add-cc2e-531b-8674-4feb26904f3d  HW 3 - Laplace Transforms and Intro to Control...  Sameer Shroff         5 2022-09-07 20:37:59                    (2363, 1621, 1323, 682) 2025-12-02 07:58:08                   1  b907d592332785225f53963d7e64d3379ba273adfb78ba...  HW 3 - Laplace Transforms and Intro to Control...  [0.17491297, 0.09576405, -0.016945682, -0.1201...  chunked document 2025-11-26 11:27:12  .\data\HW 3 - Laplace Transforms and Intro to ...          3     .pdf
8  0.757619  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  Carnegie Mellon University 24-451: Feedback Co...  7fc073a6-6e1e-56c1-8e0e-9cadc79ce416                        HW 5 - Exam 1 in Matlab.pdf  Sameer Shroff         3 2024-09-25 17:53:25                         (1749, 2024, 1216) 2025-12-02 07:58:09                   1  910573961d42ea022be07ca314325b4400a963f89e1795...                        HW 5 - Exam 1 in Matlab.pdf  [0.27967873, -0.16479258, 0.14392321, -0.25018...  chunked document 2025-11-26 11:27:12                 .\data\HW 5 - Exam 1 in Matlab.pdf          0     .pdf
9  0.757619  7fc073a6-6e1e-56c1-8e0e-9cadc79ce416  Carnegie Mellon University 24-451: Feedback Co...  7fc073a6-6e1e-56c1-8e0e-9cadc79ce416                        HW 5 - Exam 1 in Matlab.pdf  Sameer Shroff         0 2024-09-25 17:53:25                         (1749, 2024, 1216) 2025-12-02 07:58:09                   1  910573961d42ea022be07ca314325b4400a963f89e1795...                        HW 5 - Exam 1 in Matlab.pdf  [0.27967873, -0.16479258, 0.14392321, -0.25018...     full document 2025-11-26 11:27:12                 .\data\HW 5 - Exam 1 in Matlab.pdf         -1     .pdf

In [76]:
query ="what options do I have to install matlab in detail"
response = VD.query(query, k = 10)
print(response.content)

found 10 similar documents
You have the following options to install MATLAB:
1. Download and install MATLAB locally from https://www.cmu.edu/computing/software/all/matlab/.
2. Run MATLAB online through a browser at https://www.mathworks.com/products/matlab-online.html.
3. Run MATLAB through a Virtual Andrew session at https://www.cmu.edu/computing/services/endpoint/software/managed-desktops/how-to/virtual-andrew.html. (source: HW 1 - Cave Flyer.pdf)

In [77]:
import source.cluster as cluster_analysis
importlib.reload(cluster_analysis)

CA = cluster_analysis.ClusterAnalyis(VD)


CA.calculate_pca()
CA.perform_kmeans_clustering(n_clusters=5)


df = VD.get(keep_cols = ['id', 'kmeans_cluster_idx', 'pca_embedding'])

embeddings matrix is (43, 384)
pca matrix is (43, 43)
updated metadata for 43 records for the following keys: {'pca_embedding'}
embeddings matrix is (43, 43)
performed kmeans clustering with 5 clusters
kmeans_cluster_idx
4     7
3     7
2     3
1    24
0     2
Name: count, dtype: int64
updated metadata for 43 records for the following keys: {'kmeans_cluster_idx'}

In [78]:
df = VD.get(keep_cols = ['id', 'kmeans_cluster_idx', 'pca_embedding'])
df

                                      id  kmeans_cluster_idx                                      pca_embedding
0   b620ba0a-f2d0-5893-8fb0-f5611726f076                   4  [-0.96194005, -0.08295372, 0.077238485, 0.0724...
1   d00a351a-96b3-560b-8b31-f7dab9abc247                   4  [-0.8921507, -0.031904317, 0.0038818545, 0.097...
2   ac16fb33-1007-5f21-badf-51326739eae1                   4  [-0.85351557, -0.029737614, 0.09558281, 0.0398...
3   6e75dfa6-61ce-5d73-9f0b-97e593b36e70                   4  [-0.77306896, -0.076380834, 0.13878925, -0.124...
4   7f7ee21b-13c6-5bd6-927b-45ae4a2d217a                   4  [-0.8280119, -0.04965237, -0.06226323, -0.0801...
5   2443d291-d7bc-5b92-a554-04af388319a1                   4  [-0.7999373, -0.023013782, 0.117752, -0.113043...
6   6387ac27-fb24-5a6b-9830-4c22a1923477                   4  [-0.9174982, -0.066288225, 0.08287432, 0.04778...
7   278661f7-8e8d-5a6b-b0e9-3a795d3c1d75                   3  [0.19473673, -0.05693338, -0.45915636, -0.0141...
8   84d1843d-1bd1-53b8-ae55-2c2c939cdb37                   3  [0.1943941, -0.04695838, -0.4651027, -0.022004...
9   a6a533b9-7542-5de9-997e-a8bf62a2567d                   3  [0.024809647, 0.15658154, -0.5019879, -0.17413...
10  8db318ca-8016-52e1-895a-b94b73bf5866                   3  [-0.034289915, 0.2434148, -0.4520421, -0.19045...
11  6b05026a-6866-5d10-9f05-55d96590efd0                   2  [0.15301578, 0.11162845, 0.0072885994, 0.45425...
12  b5d3bc77-d338-5180-965f-5f40c72baed2                   2  [0.15301578, 0.11162845, 0.0072885994, 0.45425...
13  31d1eafa-c729-54c6-ac3d-5255371c96e7                   2  [0.07369657, 0.2930621, -0.040320616, 0.564432...
14  af0e56d4-5e39-52fb-9a06-f6bb1c058b49                   1  [0.015624386, 0.43334192, 0.02293816, 0.322798...
15  7b199add-cc2e-531b-8674-4feb26904f3d                   3  [0.064318426, -0.5490531, -0.38938266, 0.13844...
16  2cd378ca-b422-51cb-9571-1bd060000b9b                   3  [0.064318426, -0.5490531, -0.38938266, 0.13844...
17  a15a1017-2f3c-53dd-b46b-b1e946be0626                   1  [0.11228248, -0.16789097, 0.029587485, -0.0621...
18  f2b9c5c1-9186-5c6f-a312-18e0acb3184c                   1  [0.12583521, -0.16315621, 0.14857318, -0.23560...
19  2f69e529-3bc2-5a92-874b-b6721ac6adf4                   1  [0.17491297, 0.09576405, -0.016945682, -0.1201...
20  02ef51c4-8f87-552e-8832-f72ed1df50ef                   0  [-0.06201859, 0.49321517, -0.17453222, 0.03661...
21  b48ccef8-b823-580c-b6a0-bda17e9a9390                   1  [0.19646622, 0.016178811, -0.0045460826, -0.08...
22  07d9494a-ea63-53ef-8cb4-07742beb9abb                   1  [0.19646622, 0.016178811, -0.0045460826, -0.08...
23  62b4072a-1df9-55d9-a9a3-457666485e0c                   0  [0.13933556, 0.17940916, 0.16352536, -0.253914...
24  7fc073a6-6e1e-56c1-8e0e-9cadc79ce416                   1  [0.27967873, -0.16479258, 0.14392321, -0.25018...
25  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce                   1  [0.27967873, -0.16479258, 0.14392321, -0.25018...
26  fd404feb-816b-5840-b735-a1266097fa05                   1  [0.2537409, -0.025403805, 0.22249834, -0.11619...
27  a8aa1388-28e7-5e69-9266-2b9048abfce8                   1  [0.21804263, 0.13514696, 0.29423964, 0.1063230...
28  566ede87-b00d-52ae-9f8d-d8ee8b019ab8                   1  [0.28498974, -0.10141616, 0.19842438, -0.00479...
29  633cf765-5101-537d-944a-50becd881f81                   1  [0.28498974, -0.10141616, 0.19842438, -0.00479...
30  c6aeca0f-6ea7-585e-b995-1cf9b71baef3                   1  [0.3097695, 0.1719774, 0.03516554, -0.00881333...
31  ad157204-5bfd-5c8f-b7e0-8e1091b814ab                   1  [0.3407485, -0.011094809, 0.08646353, 0.057305...
32  a9b7e972-fbf0-5ff5-af3c-19fba77410f6                   1  [0.3407485, -0.011094809, 0.08646353, 0.057305...
33  83b8a84b-a11d-5cb1-b2d7-758e1d86b895                   1  [0.078053735, -0.02825598, -0.016325193, 0.101...
34  6da8d02a-6ffa-5410-8915-cb4992b2a3e0                   1  [0.2710822, -0.08516913, 0.040894255, -0.08631...
35  34d76a86-10c7-52c4-b9fa-a71985820b17                   1  [0.19296512, 0.089894734, 0.0039551253, -0.227...
36  27094245-284d-571e-8e0d-4f4a1ebb03f6                   3  [-0.019669985, 0.2168204, -0.0022083966, -0.19...
37  4b983cb4-395e-5079-a6f3-89783cc878ac                   1  [0.21575166, 0.028616017, 0.07063402, -0.21752...
38  c1c38fd3-bf54-54af-b292-b4bdda4fb016                   1  [-0.017693827, 0.521249, -0.05020807, -0.27623...
39  7cf34e95-db98-511b-ac82-8e0595b014d9                   1  [0.2664775, -0.13435142, 0.22354427, 0.1613038...
40  c6566691-5068-5848-a341-39c0910c40bc                   1  [0.2664775, -0.13435142, 0.22354427, 0.1613038...
41  70354a5d-490e-59e0-8973-ed82cf0995a8                   1  [0.19668584, -0.22949646, 0.080766074, 0.08691...
42  9e5afc2a-3f98-5a8b-b375-24fa92c0cd58                   1  [0.19668584, -0.22949646, 0.080766074, 0.08691...

In [79]:
id = parsers.generate_document_uuid_from_path(files[0])
r = VD.collection.get(ids = id, include = [])
id_exists = len(r['ids'])>0

print(id_exists)

True