In [34]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import shroff_rag
import importlib
import os
import glob
import parsers

importlib.reload(shroff_rag)
importlib.reload(parsers)

In [35]:
device = "cuda"
database_folder = "./database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

DS = shroff_rag.DataStore(device, database_folder)
DS.info()
DS.clear_collections()
DS.create_collection()

collections: [Collection(name=documents)]
deleted data in Collection(name=documents)
created collection: Collection(name=documents) with 0 documents

In [36]:
glob_pattern = os.path.join('.', 'data', '*.pdf')
files = glob.glob(glob_pattern)

for file in files:
   DS.add_document(file)

- added .\data\HW 1 - Cave Flyer.pdf
   - added 5 chunks from .\data\HW 1 - Cave Flyer.pdf
- added .\data\HW 2 - Complex Numbers.pdf
   - added 6 chunks from .\data\HW 2 - Complex Numbers.pdf
- added .\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
   - added 8 chunks from .\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
- added .\data\HW 4 - Linearization and Dynamic Response.pdf
   - added 3 chunks from .\data\HW 4 - Linearization and Dynamic Response.pdf
- added .\data\HW 5 - Exam 1 in Matlab.pdf
   - added 7 chunks from .\data\HW 5 - Exam 1 in Matlab.pdf
- added .\data\HW 6 - Routh Array and Root Locus.pdf
   - added 4 chunks from .\data\HW 6 - Routh Array and Root Locus.pdf
- added .\data\HW 7 - Design Challenges.pdf
   - added 13 chunks from .\data\HW 7 - Design Challenges.pdf
- added .\data\HW 8 - Nyquist Stability.pdf
   - added 2 chunks from .\data\HW 8 - Nyquist Stability.pdf
- added .\data\HW 9 - Stability Margins and Compensation.pdf
   - added 2 chunks from .\data\HW 9 - Stability Margins and Compensation.pdf

In [37]:
DS.info()

collections: [Collection(name=documents)]

In [38]:
query ="how do I install matlab"
df_results = DS.search(query, k = 10)
df_results

found 10 similar documents

   distance                                           basename                                    id           modification_date         author       source_type                               page_lengths  chunk_idx               creation_date                             source_id                                               hash                 upload_date                                           fullpath file_ext pca  N_chunks                                           document
0  0.467617                              HW 1 - Cave Flyer.pdf  394142de-0d69-4e91-bdaa-ae976dbd4021  2024-08-25 16:26:44.119668  Sameer Shroff  chunked document                           [974, 2735, 291]          0  2025-11-26 11:27:12.507327  7353459a-33c2-544c-81f2-4e8877cddfcc  d235a1898843e3a439eabc58b387565f659900d5644604...  2025-11-28 23:14:50.171100                       .\data\HW 1 - Cave Flyer.pdf     .pdf             5  Carnegie Mellon University 24-451: Feedback Co...
1  0.477226                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc  2024-08-25 16:26:44.119668  Sameer Shroff     full document                           [974, 2735, 291]         -1  2025-11-26 11:27:12.507327  7353459a-33c2-544c-81f2-4e8877cddfcc  d235a1898843e3a439eabc58b387565f659900d5644604...  2025-11-28 23:14:50.171100                       .\data\HW 1 - Cave Flyer.pdf     .pdf             0  Carnegie Mellon University 24-451: Feedback Co...
2  0.660489                        HW 5 - Exam 1 in Matlab.pdf  9bfa7790-7341-4857-b890-2e87b4cedd2c  2024-09-25 17:53:25.497000  Sameer Shroff  chunked document                         [1749, 2024, 1216]          3  2025-11-26 11:27:12.511332  aca9ef5a-8288-54e0-8231-4268d682efd2  910573961d42ea022be07ca314325b4400a963f89e1795...  2025-11-28 23:14:51.363468                 .\data\HW 5 - Exam 1 in Matlab.pdf     .pdf             7  j. What happens as K increases?  Show and exam...
3  0.697031  HW 3 - Laplace Transforms and Intro to Control...  da001141-ea8d-4d8d-b75f-cf9a95cf6ad9  2022-09-07 20:37:59.854000  Sameer Shroff  chunked document                    [2363, 1621, 1323, 682]          1  2025-11-26 11:27:12.509331  92843a15-ddf5-51b5-b851-ed3b159a4e25  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2025-11-28 23:14:50.638528  .\data\HW 3 - Laplace Transforms and Intro to ...     .pdf             8  not discussed in class).   \n4. Typical contro...
4  0.697794              HW 6 - Routh Array and Root Locus.pdf  fd2f5075-64bf-478d-9dcd-9293215ee6af  2023-10-04 17:23:37.193000  Sameer Shroff  chunked document                                [2191, 957]          2  2025-11-26 11:27:12.513349  7f0fa013-0289-5477-987f-29511a387622  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  2025-11-28 23:14:51.595043       .\data\HW 6 - Routh Array and Root Locus.pdf     .pdf             4  Do problems:  \n• # 4.  Hint: for the closed l...
5  0.709502                         HW 2 - Complex Numbers.pdf  19a80632-56f0-41bb-beb0-2be0cbc8f17b  2024-08-27 20:24:40.731488  Sameer Shroff  chunked document                          [1937, 1550, 600]          3  2025-11-26 11:27:12.508334  3dc8bb69-454a-535c-9815-02ae4e274a4f  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  2025-11-28 23:14:50.380201                  .\data\HW 2 - Complex Numbers.pdf     .pdf             6  complex number should you multiply by?  Show t...
6  0.712724                       HW 7 - Design Challenges.pdf  22956f36-ad62-4a5c-b353-37891dfa2f1f  2022-10-23 12:31:27.302366  Sameer Shroff  chunked document  [1352, 1462, 1842, 401, 1634, 1157, 1138]          7  2025-11-26 11:27:12.514347  8a5a4e88-6b39-5898-8682-6953f1a90da7  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2025-11-28 23:14:51.774177                .\data\HW 7 - Design Challenges.pdf     .pdf            13  Carnegie Mellon University 24-451: Feedback Co...
7  0.726754                       HW 7 - Design Challenges.pdf  285e3acf-786f-4c40-93bf-85d188976245  2022-10-23 12:31:27.302366  Sameer Shroff  chunked document  [1352, 1462, 1842, 401, 1634, 1157, 1138]          0  2025-11-26 11:27:12.514347  8a5a4e88-6b39-5898-8682-6953f1a90da7  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2025-11-28 23:14:51.774177                .\data\HW 7 - Design Challenges.pdf     .pdf            13  Carnegie Mellon University 24-451: Feedback Co...
8  0.727744  HW 3 - Laplace Transforms and Intro to Control...  fe046030-3555-4a4f-823b-15d5435763ce  2022-09-07 20:37:59.854000  Sameer Shroff  chunked document                    [2363, 1621, 1323, 682]          2  2025-11-26 11:27:12.509331  92843a15-ddf5-51b5-b851-ed3b159a4e25  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2025-11-28 23:14:50.638528  .\data\HW 3 - Laplace Transforms and Intro to ...     .pdf             8  inputs and outputs of the function, listed bel...
9  0.738187                         HW 2 - Complex Numbers.pdf  f29d3e18-b0d6-4bf4-b225-db026842ab1b  2024-08-27 20:24:40.731488  Sameer Shroff  chunked document                          [1937, 1550, 600]          4  2025-11-26 11:27:12.508334  3dc8bb69-454a-535c-9815-02ae4e274a4f  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  2025-11-28 23:14:50.380201                  .\data\HW 2 - Complex Numbers.pdf     .pdf             6  𝑐1 + 𝑐2𝑗 by 𝜃 degrees.  Describe your methodol...

In [39]:
query ="what options do I have to install matlab in detail"
response = DS.query(query, k = 10)
print(response.content)

found 10 similar documents
You have the following options to install MATLAB:
1. Download and install MATLAB locally from https://www.cmu.edu/computing/software/all/matlab/.
2. Run MATLAB online through a browser at https://www.mathworks.com/products/matlab-online.html.
3. Run MATLAB through a Virtual Andrew session at https://www.cmu.edu/computing/services/endpoint/software/managed-desktops/how-to/virtual-andrew.html.
(source: HW 1 - Cave Flyer.pdf)

In [40]:
DS.compute_pca()

embeddings matrix is (59, 384)
pca matrix is (59, 59)
saved pca data to vector database

In [41]:
labels, inertia, df_pca = DS.run_kmeans(n_clusters = 3)
df_pca

                                         pca_0     pca_1     pca_2     pca_3     pca_4     pca_5     pca_6     pca_7     pca_8     pca_9    pca_10    pca_11    pca_12    pca_13    pca_14    pca_15    pca_16    pca_17    pca_18    pca_19    pca_20    pca_21    pca_22    pca_23    pca_24    pca_25    pca_26    pca_27    pca_28    pca_29    pca_30    pca_31    pca_32    pca_33    pca_34    pca_35    pca_36    pca_37    pca_38    pca_39    pca_40    pca_41    pca_42    pca_43    pca_44    pca_45    pca_46    pca_47    pca_48    pca_49    pca_50    pca_51    pca_52    pca_53    pca_54    pca_55    pca_56  pca_57  pca_58
7353459a-33c2-544c-81f2-4e8877cddfcc -0.097473  0.023911  0.404297  0.123596 -0.044678 -0.191650 -0.105103  0.284668  0.090149  0.191895  0.212036  0.049622  0.157959 -0.012924 -0.103882 -0.110474 -0.038361  0.108032  0.043884 -0.095276  0.120422 -0.054108 -0.064026 -0.006313 -0.025238 -0.047363 -0.026718  0.067017  0.056427 -0.009048  0.030624  0.017227  0.001927  0.021255 -0.014137 -0.010353  0.017822  0.005661 -0.017075 -0.024445 -0.011375 -0.004311 -0.007507  0.016754  0.008163  0.004921 -0.009583  0.005924 -0.012108 -0.001997  0.002077 -0.002522  0.007568  0.013435  0.026901  0.038269  0.001522    -0.0     0.0
3dc8bb69-454a-535c-9815-02ae4e274a4f  0.379395 -0.236328  0.203735  0.020264 -0.132568  0.264648  0.022995  0.056427 -0.270508 -0.085876  0.068726 -0.038147 -0.092590 -0.161377 -0.008499 -0.092163 -0.024323 -0.068298  0.068970  0.008553 -0.041504 -0.010902 -0.028015  0.110962  0.002043  0.084778 -0.042358  0.046265  0.038239 -0.023895  0.049133  0.064575 -0.064758 -0.031403  0.049225 -0.031204  0.032715  0.003504  0.002792  0.024887  0.004379 -0.043365  0.014145  0.024796 -0.032166 -0.012032 -0.008881 -0.001143  0.004749 -0.000172  0.002567 -0.003546 -0.002533 -0.001260  0.005260  0.000632 -0.023254    -0.0     0.0
92843a15-ddf5-51b5-b851-ed3b159a4e25 -0.202026 -0.345703  0.504883  0.128418 -0.142334 -0.077881  0.184692 -0.223999  0.110291  0.186401 -0.299072 -0.084412 -0.107727  0.054596 -0.072449 -0.065063  0.035095  0.046326  0.080017  0.066284 -0.043060  0.013184  0.049896 -0.003101  0.000798 -0.000573 -0.016876 -0.018890 -0.021057  0.005207  0.005890 -0.016312 -0.001168  0.018341  0.025421  0.013672 -0.002172 -0.024200 -0.015480  0.012848 -0.001431  0.007488 -0.011650 -0.005959  0.016541 -0.009270  0.020523  0.005798  0.009270 -0.054596  0.050201 -0.039642  0.044678  0.002205 -0.003706 -0.002375  0.000022    -0.0     0.0
eb7dbac7-1c3e-59c6-ba88-06afd7217d81 -0.147705 -0.039734  0.125000 -0.253174 -0.197144  0.105835 -0.268555 -0.065979  0.044342 -0.213501  0.076904 -0.341064  0.032623 -0.042175  0.004562 -0.058899  0.076111  0.081421 -0.123230 -0.022675  0.030365 -0.037170 -0.016342  0.031982  0.079956 -0.078674 -0.041473 -0.073425 -0.057800  0.032593  0.004246  0.001627  0.018616  0.034302  0.023117  0.007957 -0.048462 -0.006432 -0.014511 -0.010651  0.017853 -0.003691 -0.001976 -0.008224 -0.000726 -0.004879 -0.014091  0.002180 -0.000116  0.006020  0.001966 -0.001649  0.001304 -0.000312 -0.000065 -0.000304  0.000169    -0.0    -0.0
aca9ef5a-8288-54e0-8231-4268d682efd2 -0.190430 -0.133057 -0.096863 -0.204712 -0.094116 -0.157104  0.200562  0.118103 -0.053558  0.097595 -0.009293 -0.133301  0.066956  0.013596  0.152466  0.131104 -0.050476 -0.009880  0.058533 -0.105652 -0.065857 -0.055542 -0.013664  0.111450  0.010101  0.001257  0.003708  0.022827 -0.022614  0.040436  0.016708 -0.012489  0.084595 -0.067810 -0.031738  0.078003 -0.007553  0.028473  0.023453 -0.015717  0.018524 -0.022537 -0.005428  0.002623 -0.041077 -0.027939 -0.008636  0.031586  0.000028 -0.067871  0.026489  0.004845 -0.064209 -0.003679  0.000682  0.002855  0.000837    -0.0     0.0
7f0fa013-0289-5477-987f-29511a387622 -0.123108 -0.272949 -0.099243 -0.112366 -0.015457 -0.017975 -0.184204 -0.045715 -0.048340 -0.075684 -0.106812  0.147217 -0.056030  0.073364 -0.156006  0.125366 -0.193115 -0.020279 -0.123047 -0.074402  0.021027 -0.007038 -0.014282  0.062103 -0.140259  0.019592 -0.103699  0.032104  0.046173  0.079285  0.013756 -0.014771  0.014153  0.022018  0.014580  0.000215 -0.041290 -0.050598 -0.011856  0.025299 -0.027969  0.012009  0.002075 -0.027939  0.030029  0.027374 -0.002907  0.010834  0.015060 -0.012421 -0.064880 -0.064270 -0.016495  0.004490  0.000653 -0.000857 -0.000174    -0.0     0.0
8a5a4e88-6b39-5898-8682-6953f1a90da7 -0.033386 -0.207031 -0.095337  0.043060  0.011024 -0.074829 -0.091003  0.202393 -0.097473 -0.097839 -0.120789  0.020432  0.024307  0.088562  0.053894 -0.118774  0.101746 -0.012848 -0.016586  0.120972  0.045227  0.047791 -0.009941  0.044128 -0.005047  0.012871  0.116638 -0.014740  0.011490  0.044098 -0.018387 -0.015388  0.054382  0.053192  0.036530  0.016083  0.037842 -0.010239  0.002043  0.036163  0.002337 -0.004742 -0.046722  0.027618  0.010063  0.012650 -0.027008 -0.091064 -0.038635 -0.060669 -0.053192  0.037445  0.017197  0.010063 -0.019028  0.009598 -0.001311    -0.0     0.0
b58c24f9-36c9-5332-8d5c-c363e1ab26be -0.012215 -0.343262 -0.161011  0.113770  0.010155 -0.145142 -0.020691 -0.105591 -0.008057 -0.076477  0.068481  0.179077  0.081726 -0.161377  0.141479 -0.049103  0.051117  0.086365  0.042786 -0.022949 -0.054474  0.016586  0.033752 -0.076294  0.037201 -0.097900 -0.115356  0.004154  0.019638 -0.060638 -0.077209 -0.047363  0.025330 -0.026367  0.049133 -0.017288 -0.020538  0.021561 -0.036255  0.050781 -0.030807  0.000293  0.004009 -0.019684 -0.009697 -0.035248 -0.018814  0.011269 -0.008797 -0.031860 -0.027328  0.019409  0.014427 -0.008537  0.037567 -0.023300  0.001309    -0.0     0.0
0eacdba8-9efd-59ce-816a-366d8cf519a9 -0.171631 -0.300293 -0.043915  0.240723  0.167114 -0.070374  0.006599 -0.133789 -0.120117  0.056091  0.248901 -0.097595  0.010117 -0.054474 -0.038605  0.197998  0.075989  0.063232 -0.047119  0.128052  0.081299  0.087097  0.083008 -0.035797 -0.006756  0.061157  0.020676 -0.008873  0.012238  0.024933  0.024551  0.037628 -0.031372 -0.009079 -0.001306  0.029282 -0.000233  0.020813  0.015388 -0.058655 -0.011139  0.008575 -0.007175  0.008621 -0.006001  0.032623  0.010651 -0.009827  0.011314 -0.005291 -0.010109 -0.003567  0.005573 -0.059906 -0.002028  0.013710  0.000299    -0.0     0.0

In [46]:
id = DS.collection.get(limit = 1)['ids'][0]
df = DS.search_by_id(id, k =10, where = {'source_type':'full document'})
print(df)

       distance                                           basename                                    id         author                                                pca               creation_date                               page_lengths    source_type  chunk_idx                                               hash                             source_id                 upload_date           modification_date                                           fullpath  N_chunks file_ext                                           document
0  3.576279e-07                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc  Sameer Shroff  [-0.09745040145997666, 0.0239056972048863, 0.4...  2025-11-26 11:27:12.507327                           [974, 2735, 291]  full document         -1  d235a1898843e3a439eabc58b387565f659900d5644604...  7353459a-33c2-544c-81f2-4e8877cddfcc  2025-11-28 23:14:50.171100  2024-08-25 16:26:44.119668                       .\data\HW 1 - Cave Flyer.pdf         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
1  4.009807e-01                       HW 7 - Design Challenges.pdf  8a5a4e88-6b39-5898-8682-6953f1a90da7  Sameer Shroff  [-0.033397547548804814, -0.2070083680654652, -...  2025-11-26 11:27:12.514347  [1352, 1462, 1842, 401, 1634, 1157, 1138]  full document         -1  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  8a5a4e88-6b39-5898-8682-6953f1a90da7  2025-11-28 23:14:51.774177  2022-10-23 12:31:27.302366                .\data\HW 7 - Design Challenges.pdf         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
2  4.437943e-01                        HW 5 - Exam 1 in Matlab.pdf  aca9ef5a-8288-54e0-8231-4268d682efd2  Sameer Shroff  [-0.1904676541166523, -0.13307204027003494, -0...  2025-11-26 11:27:12.511332                         [1749, 2024, 1216]  full document         -1  910573961d42ea022be07ca314325b4400a963f89e1795...  aca9ef5a-8288-54e0-8231-4268d682efd2  2025-11-28 23:14:51.363468  2024-09-25 17:53:25.497000                 .\data\HW 5 - Exam 1 in Matlab.pdf         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
3  4.689484e-01      HW 9 - Stability Margins and Compensation.pdf  0eacdba8-9efd-59ce-816a-366d8cf519a9  Sameer Shroff  [-0.1715749821662112, -0.300254976348345, -0.0...  2025-11-26 11:27:12.516346                                     [1682]  full document         -1  9a6a2b527b59828fc47564fb9c95b4c5a24597e9d328fb...  0eacdba8-9efd-59ce-816a-366d8cf519a9  2025-11-28 23:14:53.283115  2024-10-23 09:08:41.972093  .\data\HW 9 - Stability Margins and Compensati...         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
4  4.818359e-01                       HW 8 - Nyquist Stability.pdf  b58c24f9-36c9-5332-8d5c-c363e1ab26be  Sameer Shroff  [-0.012212717280018255, -0.3432190166218551, -...  2025-11-26 11:27:12.515346                                     [1230]  full document         -1  4623910fab2a942e48d87d03a7a14a78f2a37819210fa8...  b58c24f9-36c9-5332-8d5c-c363e1ab26be  2025-11-28 23:14:53.130701  2022-10-23 12:32:44.015152                .\data\HW 8 - Nyquist Stability.pdf         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
5  4.869819e-01      HW 4 - Linearization and Dynamic Response.pdf  eb7dbac7-1c3e-59c6-ba88-06afd7217d81  Sameer Shroff  [-0.14765964738550874, -0.039737873715005353, ...  2025-11-26 11:27:12.510332                                [1457, 659]  full document         -1  c1f105d224226dbd40b5158fd249c8a06f7711bbd80f9b...  eb7dbac7-1c3e-59c6-ba88-06afd7217d81  2025-11-28 23:14:50.958191         2020-09-23 07:28:23  .\data\HW 4 - Linearization and Dynamic Respon...         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
6  4.988220e-01  HW 3 - Laplace Transforms and Intro to Control...  92843a15-ddf5-51b5-b851-ed3b159a4e25  Sameer Shroff  [-0.20201848082993792, -0.3458179490897861, 0....  2025-11-26 11:27:12.509331                    [2363, 1621, 1323, 682]  full document         -1  b907d592332785225f53963d7e64d3379ba273adfb78ba...  92843a15-ddf5-51b5-b851-ed3b159a4e25  2025-11-28 23:14:50.638528  2022-09-07 20:37:59.854000  .\data\HW 3 - Laplace Transforms and Intro to ...         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
7  5.028403e-01              HW 6 - Routh Array and Root Locus.pdf  7f0fa013-0289-5477-987f-29511a387622  Sameer Shroff  [-0.12312544081913634, -0.272924053555092, -0....  2025-11-26 11:27:12.513349                                [2191, 957]  full document         -1  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  7f0fa013-0289-5477-987f-29511a387622  2025-11-28 23:14:51.595043  2023-10-04 17:23:37.193000       .\data\HW 6 - Routh Array and Root Locus.pdf         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...
8  5.448520e-01                         HW 2 - Complex Numbers.pdf  3dc8bb69-454a-535c-9815-02ae4e274a4f  Sameer Shroff  [0.37945585105624025, -0.23634997581372721, 0....  2025-11-26 11:27:12.508334                          [1937, 1550, 600]  full document         -1  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  3dc8bb69-454a-535c-9815-02ae4e274a4f  2025-11-28 23:14:50.380201  2024-08-27 20:24:40.731488                  .\data\HW 2 - Complex Numbers.pdf         0     .pdf  Carnegie Mellon University 24-451: Feedback Co...

In [43]:
import pandas as pd

id = DS.collection.get(limit = 1)['ids'][0]
r = DS.collection.get(id, include = ['embeddings'])
embedding = r['embeddings']
results = DS.collection.query(query_embeddings=embedding, include=['distances', 'metadatas', 'documents'])
df_results= shroff_rag._results_to_df(results)[0]
df_results = df_results.sort_values('distance')
df_results

       distance                                           basename                                    id         author                             source_id       source_type               creation_date                                                pca           modification_date  chunk_idx                                           fullpath file_ext                                               hash                               page_lengths  N_chunks                 upload_date                                           document
0  3.576279e-07                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc  Sameer Shroff  7353459a-33c2-544c-81f2-4e8877cddfcc     full document  2025-11-26 11:27:12.507327  [-0.09745040145997666, 0.0239056972048863, 0.4...  2024-08-25 16:26:44.119668         -1                       .\data\HW 1 - Cave Flyer.pdf     .pdf  d235a1898843e3a439eabc58b387565f659900d5644604...                           [974, 2735, 291]         0  2025-11-28 23:14:50.171100  Carnegie Mellon University 24-451: Feedback Co...
1  6.156325e-03                              HW 1 - Cave Flyer.pdf  394142de-0d69-4e91-bdaa-ae976dbd4021  Sameer Shroff  7353459a-33c2-544c-81f2-4e8877cddfcc  chunked document  2025-11-26 11:27:12.507327  [-0.09567961068889143, 0.029872929615534234, 0...  2024-08-25 16:26:44.119668          0                       .\data\HW 1 - Cave Flyer.pdf     .pdf  d235a1898843e3a439eabc58b387565f659900d5644604...                           [974, 2735, 291]         5  2025-11-28 23:14:50.171100  Carnegie Mellon University 24-451: Feedback Co...
2  3.589152e-01  HW 3 - Laplace Transforms and Intro to Control...  da001141-ea8d-4d8d-b75f-cf9a95cf6ad9  Sameer Shroff  92843a15-ddf5-51b5-b851-ed3b159a4e25  chunked document  2025-11-26 11:27:12.509331  [-0.14951696490511152, 0.02112588252143664, 0....  2022-09-07 20:37:59.854000          1  .\data\HW 3 - Laplace Transforms and Intro to ...     .pdf  b907d592332785225f53963d7e64d3379ba273adfb78ba...                    [2363, 1621, 1323, 682]         8  2025-11-28 23:14:50.638528  not discussed in class).   \n4. Typical contro...
3  3.937255e-01                       HW 7 - Design Challenges.pdf  285e3acf-786f-4c40-93bf-85d188976245  Sameer Shroff  8a5a4e88-6b39-5898-8682-6953f1a90da7  chunked document  2025-11-26 11:27:12.514347  [-0.02772100684287592, -0.20169627866021034, -...  2022-10-23 12:31:27.302366          0                .\data\HW 7 - Design Challenges.pdf     .pdf  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  [1352, 1462, 1842, 401, 1634, 1157, 1138]        13  2025-11-28 23:14:51.774177  Carnegie Mellon University 24-451: Feedback Co...
4  4.009807e-01                       HW 7 - Design Challenges.pdf  8a5a4e88-6b39-5898-8682-6953f1a90da7  Sameer Shroff  8a5a4e88-6b39-5898-8682-6953f1a90da7     full document  2025-11-26 11:27:12.514347  [-0.033397547548804814, -0.2070083680654652, -...  2022-10-23 12:31:27.302366         -1                .\data\HW 7 - Design Challenges.pdf     .pdf  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  [1352, 1462, 1842, 401, 1634, 1157, 1138]         0  2025-11-28 23:14:51.774177  Carnegie Mellon University 24-451: Feedback Co...
5  4.276317e-01              HW 6 - Routh Array and Root Locus.pdf  fd2f5075-64bf-478d-9dcd-9293215ee6af  Sameer Shroff  7f0fa013-0289-5477-987f-29511a387622  chunked document  2025-11-26 11:27:12.513349  [-0.031672400647115385, -0.12534593047786177, ...  2023-10-04 17:23:37.193000          2       .\data\HW 6 - Routh Array and Root Locus.pdf     .pdf  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...                                [2191, 957]         4  2025-11-28 23:14:51.595043  Do problems:  \n• # 4.  Hint: for the closed l...
6  4.437943e-01                        HW 5 - Exam 1 in Matlab.pdf  aca9ef5a-8288-54e0-8231-4268d682efd2  Sameer Shroff  aca9ef5a-8288-54e0-8231-4268d682efd2     full document  2025-11-26 11:27:12.511332  [-0.1904676541166523, -0.13307204027003494, -0...  2024-09-25 17:53:25.497000         -1                 .\data\HW 5 - Exam 1 in Matlab.pdf     .pdf  910573961d42ea022be07ca314325b4400a963f89e1795...                         [1749, 2024, 1216]         0  2025-11-28 23:14:51.363468  Carnegie Mellon University 24-451: Feedback Co...
7  4.439000e-01                       HW 7 - Design Challenges.pdf  e737a17f-4fcc-4290-879f-9cb830aa77f5  Sameer Shroff  8a5a4e88-6b39-5898-8682-6953f1a90da7  chunked document  2025-11-26 11:27:12.514347  [-0.14179743010144524, -0.10353334333602214, -...  2022-10-23 12:31:27.302366          4                .\data\HW 7 - Design Challenges.pdf     .pdf  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  [1352, 1462, 1842, 401, 1634, 1157, 1138]        13  2025-11-28 23:14:51.774177  Carnegie Mellon University 24-451: Feedback Co...
8  4.447445e-01                        HW 5 - Exam 1 in Matlab.pdf  3b9b865e-dadd-4aa3-8945-bfb1a7d7fa3f  Sameer Shroff  aca9ef5a-8288-54e0-8231-4268d682efd2  chunked document  2025-11-26 11:27:12.511332  [-0.17971123092363642, -0.13044921506346033, -...  2024-09-25 17:53:25.497000          0                 .\data\HW 5 - Exam 1 in Matlab.pdf     .pdf  910573961d42ea022be07ca314325b4400a963f89e1795...                         [1749, 2024, 1216]         7  2025-11-28 23:14:51.363468  Carnegie Mellon University 24-451: Feedback Co...
9  4.689484e-01      HW 9 - Stability Margins and Compensation.pdf  0eacdba8-9efd-59ce-816a-366d8cf519a9  Sameer Shroff  0eacdba8-9efd-59ce-816a-366d8cf519a9     full document  2025-11-26 11:27:12.516346  [-0.1715749821662112, -0.300254976348345, -0.0...  2024-10-23 09:08:41.972093         -1  .\data\HW 9 - Stability Margins and Compensati...     .pdf  9a6a2b527b59828fc47564fb9c95b4c5a24597e9d328fb...                                     [1682]         0  2025-11-28 23:14:53.283115  Carnegie Mellon University 24-451: Feedback Co...